class PC_Math abstract
{
	ClearScope Static Vector3 VecFromAngles (double angle, double pitch, double mag = 1.)
	{
		double cosp = cos(pitch);
		return (cos(angle)*cosp, sin(angle)*cosp, -sin(pitch)) * mag;
	}
	
	//[inkoalawetrust] Written by Agent_Ash, makes the Val ranging from O_Min to O_Man be crushed down to the range of N_Min and N_Max.
	//Useful for example for compressing distances to a range of 0 to 1.0.
	ClearScope Static Double LinearMap (Double Val, Double O_Min, Double O_Max, Double N_Min, Double N_Max) 
	{
		Return (Val - O_Min) * (N_Max - N_Min) / (O_Max - O_Min) + N_Min;
	}
	
	//CREDIT: RicardoLuis0
	ClearScope Static Vector3 AngleToVector3D(Double Angle, Double Pitch, Double Len = 1.0)
	{
		Return (Cos(Angle)*Cos(Pitch)*Len,Sin(Angle)*Cos(Pitch)*Len,Sin(Pitch)*Len);
	}
	
	Enum Vec3RelFlags
	{
		V3R_NOANGLE = 1 << 1, //Do not rotate based on angle.
		V3R_NOPITCH = 1 << 2, //Do not rotate based on pitch.
		V3R_NOROLL	= 1 << 3, //Do not rotate based on roll.
		
		V3R_ANGLEONLY = V3R_NOPITCH|V3R_NOROLL
	}
	
	//Like Vec3Offset, but also rotates the output vector based on the callers' angle.
	//Other: The actor to offset from.
	//Offs: The vector3 offsets to use.
	//NoPortal: Should the function account for static portals or not ?
	//Flags: See above for list of flags.
	ClearScope Static Vector3 Vec3OffsetRelative (Actor Other, Vector3 Offs, Bool NoPortal = False, Int Flags = 0)
	{
		If (!Other) Return (Double.NaN,Double.NaN,Double.NaN);
		Double Angle, Pitch, Roll;
		If (!(Flags & V3R_NOANGLE)) Angle = Other.Angle;
		If (!(Flags & V3R_NOPITCH)) Pitch = Other.Pitch;
		If (!(Flags & V3R_NOROLL)) Roll = Other.Roll;
		
		Quat Dir = Quat.FromAngles (Angle,Pitch,Roll);
		Return Level.Vec3Offset (Other.Pos,Dir * Offs,NoPortal);
	}
	
	static Vector3 RelativeToGlobalCoords(Vector3 startpos, Vector3 viewAngles, Vector3 offset, bool isPosition = true)
	{
		Quat dir = Quat.FromAngles(viewAngles.x, viewAngles.y, viewAngles.z);
		vector3 ofs = dir * (offset.x, -offset.y, offset.z);
		if (isPosition)
		{
			return Level.vec3offset(startpos, ofs);
		}
		return ofs;
	}
}

mixin class PC_BetterPickupSound
{
	override void PlayPickupSound(actor toucher)
	{
		double atten;
		int flags = CHANF_OVERLAP|CHANF_MAYBE_LOCAL;
		if(bNoAttenPickupSound) atten = ATTN_NONE;
		else atten = ATTN_NORM;
		if(toucher && toucher.CheckLocalView()) flags |= CHANF_NOPAUSE;
		toucher.A_StartSound(PickupSound,1002,flags,1.0,atten);
	}
}

mixin class PC_LocationalDamage {
	action int, name GetLimbDamage(int baseDamage, name damageType, vector3 hitPos, Actor victim, Actor inflictor, bool omnidirectional = false, double headSizeMul = 1.0) {
		int scaledDamage = baseDamage;
		name dmgType = damageType;
		double ang;
		
		ang = AbsAngle(victim.angle, atan2(victim.pos.y - hitPos.y, victim.pos.x - hitPos.x));
		
		double headPos, torsoPos, dickPos, legPos;
		double headMult, torsoMult, lowerTorsoMult, armMult, dickMult, legMult;
		bool noHead, noArm, noLeg, noDick;
		headPos = 0.80;
		torsoPos = 0.65;
		dickPos = 0.38;
		legPos = 0.40;
		
		headMult = 2.0;
		torsoMult = 1.5;
		lowerTorsoMult = 1.0;
		armMult = 0.8;
		dickMult = 1.25;
		legMult = 0.7;
		
		noArm = omnidirectional;
		
		double victimZ = victim.pos.z;
		double victimHeight = victim.ProjectilePassHeight > victim.Height ? victim.ProjectilePassHeight : victim.Height;
		
		if (hitPos.Z > victimZ + victimHeight * torsoPos) {
			if (hitPos.Z > victimZ + victimHeight * headPos / headSizeMul) {
				if(!noHead) {
					dmgtype = "Head";
					scaledDamage *= headMult;
				}
			}
			else if (!noArm && ang > 64 && ang < 128) {
				dmgtype = "Arm";
				scaledDamage *= armMult;
			}
			else {
				scaledDamage *= torsoMult;
			}
		}
		else if (hitPos.Z < victimZ + victimHeight * legPos) {
			if (!noDick && hitPos.Z > victimZ + victimHeight * dickPos) {
				dmgtype = "Dick";
				scaledDamage *= dickMult;
			}
			else if(!noLeg) {
				dmgtype = "Leg";
				scaledDamage *= legMult;
			}
		}
		else if (!noArm && ang > 64 && ang < 128) {
			dmgtype = "Arm";
			scaledDamage *= armMult;
		}
		else {
			scaledDamage *= lowerTorsoMult;
		}
		
		scaledDamage = victim.GetModifiedDamage(dmgType, scaledDamage, true, self, inflictor);
		return scaledDamage, dmgType;
	}
}
