class Deegclip : Ammo
{
	Default
	{
	  Inventory.Amount 0;
	  Inventory.MaxAmount 9;
	  Ammo.BackpackAmount 0;
	  Ammo.BackpackMaxAmount 9;
	  Inventory.Icon "RVICC0";
	  +INVENTORY.IGNORESKILL;;
	}
}

class EMagtoken : Inventory{ Default { Inventory.maxamount 1; }}

class Emagdrop : Actor
{
	Default
	{
	+FLOORCLIP;
	}

States
    {
    Spawn:
        TNT1 A 0 Nodelay
            {
                If (ACS_NamedExecuteWithResult("WeaponSwap",3) ==2)
                 {
                  A_SpawnItemEx("Revbox", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
                Else
                  {
                  A_SpawnItemEx("EmagPickup", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
            }    
        Stop;
    }
}

/*Actor EmagPickup : Custominventory
{
	Inventory.PickupSound "Deag/slide"
	Inventory.Pickupmessage "[2] - \c[Explosiveorange]Explosive magnum\c- acquired."
	-INVENTORY.ALWAYSPICKUP
	States
	{
		Spawn:
			DEAG W -1
			Stop	
		Pickup:
			TNT1 A 0 A_JumpIf(CountInv("Clip") == 0 && CountInv("JustaExMag") == 0,"Nopickup")
			TNT1 A 0
				{
				A_Giveinventory("EMagtoken",1);
				A_Giveinventory("JustaExMag",1);
				A_Takeinventory("Justarevolver",1);
				}
			Stop
		Nopickup:
			TNT1 A 0
			Fail

	}
}*/


class JustaExMag  : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "Deegclip";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "Revbullets";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 9;
		Weapon.slotnumber 2;
		Weapon.SlotPriority 30;
		Weapon.SelectionOrder 1100;
		Tag "$PC_MAGNUMTAG";
		Weapon.UpSound "Weapon/Select";
		Inventory.PickupSound "Deag/slide";
		Inventory.Pickupmessage "[2] - \c[Revolvergray]Explosive magnum\c- acquired.";
		Inventory.AltHUDIcon "DEAGW0";
		JustaWeapon.BarGraphic "MBullBar";
		JustaWeapon.CaseGraphic "MBullet";
	}
	
	action void PC_FireExMag(double spreadMod = 0) {
		A_GunFlash();
		A_AlertMonsters();
		PC_PlayPowerModSounds();
		A_StartSound("Weapons/Deeg", CHAN_WEAPON);
		PC_FireBullets("PC_ExMagProjectile", 1.5 * spreadMod, 1.5 * spreadMod);
		PC_TakeAmmo("DeegClip");
		PC_GunSmoke(0,3,3);
	}
	
	States
	{
		Spawn:
			DEAG W -1;
			Stop;
		Select:
			DEAM BA 1 A_WeaponReady(WRF_NOFIRE);
			DEAG A 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"UnzoomThenDeselect");
			DEAG A 1;
			DEAM AB 1;
			TNT1 A 0 A_lower;
			wait;
		UnzoomThenDeselect:
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_SetCrosshair(0);
			TNT1 A 0 A_StartSound("Deag/ADSOut",11);
			DEAG YX 1;
			DEAM AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Readyzoom");
			DEAG A 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Readyzoom:
			TNT1 A 0 A_GiveInventory("Weaponzoom",1);
		Readyzoom2:
			DEA9 A 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Zoomedtemp:
			DEA9 A 6 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2|WRF_NOSECONDARY);
			Goto Readyzoom;
		Unzoomedtemp:
			DEAG A 6 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2|WRF_NOSECONDARY);
			Goto Ready;
		Dryfire:
			DEAG A 4 A_startsound("Weapons/HPistolempty", 5);
			Goto ready;
		DryUnzoom:
			DEA9 A 1;
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_SetCrosshair(0);
			DEAG YXA 2;
			DEAG A 1;
			goto Dryfire;
		Fire:
			TNT1 A 0 A_JumpIfInventory("Weaponzoom",1,"FireZoom");
			TNT1 A 0 A_JumpIfInventory("Deegclip",1,1);
			Goto Dryfire;
			DEAG B 1 BRIGHT PC_FireExMag();
			DEAG C 1 BRIGHT;
			DEAG D 1 {
				A_WeaponOffset(0,38);
				PC_SpawnCasing("MagnumCasing", 16, 0, 40, frandom(2.0, 3.0), frandom(5.0, 6.0), frandom(4.0, 5.0));
				PC_QuakeCamera(3,2);
				PC_WeaponRecoil(4,6);
			}
			DEAG E 1 A_WeaponOffset(0,34);
			DEAG F 1 A_WeaponOffset(0,37);
			TNT1 A 0 A_ZoomFactor(0.999);
			DEAG G 1 A_WeaponOffset(0,35);
			DEAG H 1 A_WeaponOffset(0,34);
			TNT1 A 0 A_ZoomFactor(1.0);
			DEAG IJ 1;
			DEAG KL 1 A_WeaponReady(WRF_NOSWITCH|WRF_NOBOB);
			TNT1 A 0 A_WeaponOffset(0, 32);
			DEAG AA 1 A_WeaponReady(WRF_NOSWITCH|WRF_NOBOB);
			Goto Ready;
		Firezoom:
			TNT1 A 0 A_giveinventory("Weaponzoom",1);
			TNT1 A 0 A_JumpIfInventory("Deegclip",1,1);
			Goto DryUnzoom;
			DEA9 B 1 BRIGHT PC_FireExMag(0.33);
			DEA9 C 1 BRIGHT;
			DEA9 D 1 {
				A_WeaponOffset(0,38);
				PC_SpawnCasing("MagnumCasing", 16, 0, 48, frandom(2.0, 3.0), frandom(5.0, 6.0), frandom(4.0, 5.0));
				A_ZoomFactor(1.49, ZOOM_INSTANT);
				PC_QuakeCamera(3,2);
				PC_WeaponRecoil(3,5);
			}
			DEA9 E 1 A_WeaponOffset(0,34);
			TNT1 A 0 A_ZoomFactor(1.5);
			DEA9 F 1 A_WeaponOffset(0,37);
			DEA9 G 1 A_WeaponOffset(0,35);
			DEA9 H 1 A_WeaponOffset(0,34);
			DEA9 IJ 1;
			TNT1 A 0 A_WeaponOffset(0, 32);
			DEA9 KL 1 A_WeaponReady(WRF_NOSWITCH|WRF_NOBOB);
			DEA9 A 1 A_WeaponReady(WRF_NOSWITCH|WRF_NOBOB);
			Goto Ready;
		Reload:
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Unzoom4Reload");
			TNT1 A 0 A_JumpIfInventory("Deegclip", 9, 2);
			TNT1 A 0 A_JumpIfInventory("Revbullets", 1, "reloadwork");
			DEAG A 1;
			Goto Ready;
		UnZoom4Reload:
			TNT1 A 0 A_JumpIfInventory("Deegclip", 9, "ReadyZoom");
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_SetCrosshair(0);
			TNT1 A 0 A_StartSound("Deag/ADSOut",11);
			DEAG YX 1;
			Goto Reload;
		Reloadwork:
			DEAG A 1;
			DEAR ABCD 1;
			DEAR E 1 A_startsound("Deag/out",10,0);
			TNT1 A 0 A_FireProjectile("Pclipspawner",0,0,0,-10);
			DEAR EFGH 1;
			DEAR I 10;
			DEAR J 2;
			DEAR KLMNO 1;
			DEAR P 2;
			DEAR Q 3;
			DEAR RS 1;
			TNT1 A 0 PC_AmmoIntoMag();
			TNT1 A 0 A_startsound("Deag/In",12,0);
			DEAR TUVWX 1;
			DEAR Y 5;
			TNT1 A 0 A_startsound("Deag/slide",13,0);
			DEAR Z 1;
			DEA2 A 1;
			DEA2 B 3;
			DEA2 CDEFGH 1;
			Goto Ready;
		Altfire:
			TNT1 A 0 A_JumpIfInventory("Weaponzoom",1,"UnZoom");
			TNT1 A 0 A_GiveInventory("Weaponzoom",1);
			TNT1 A 0 A_SetCrosshair(8);
			TNT1 A 0 {
				A_StartSound("Deag/ADSIn",11);
				A_ZoomFactor(1.5);
			}
			DEAG XY 1;
			Goto Zoomedtemp;
		UnZoom:
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_SetCrosshair(0);
			TNT1 A 0 A_StartSound("Deag/ADSOut",11);
			DEAG YX 1;
			Goto UnZoomedtemp;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Unzoom4Nade");
			DEAG A 1;
			DEAM AB 1;
			Goto nadethrow;
		UnZoom4Nade:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_SetCrosshair(0);
			TNT1 A 0 A_StartSound("Deag/ADSOut",11);
			DEAG YX 1;
			DEAM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Unzoom4Mine");
			DEAG A 1;
			DEAM AB 1;
			Goto Minethrow;
		UnZoom4Mine:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_SetCrosshair(0);
			TNT1 A 0 A_StartSound("Deag/ADSOut",11);
			DEAG YX 1;
			DEAM AB 1;
			Goto Minethrow;
		Returnstate:
			DEAM BA 1;
			DEAG A 1;
			Goto Ready;
	}
}