class SMGmag : Ammo
{
	Default
	{
	  Inventory.Amount 0;
	  Inventory.MaxAmount 50;
	  Ammo.BackpackAmount 0;
	  Ammo.BackpackMaxAmount 50;
	  Inventory.Icon "CLIPB0";
	  +INVENTORY.IGNORESKILL;
  }
}

class Uzitoken : Inventory { Default { Inventory.maxamount 1; }}

class SMGDrop : Actor
{
	Default
	{
		+FLOORCLIP;
	}
States
    {
    Spawn:
        TNT1 A 0 Nodelay
            {
                If (ACS_NamedExecuteWithResult("WeaponSwap",1) ==2)
                {
                  A_SpawnItemEx("Pbox", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
                Else
                  {
                  A_SpawnItemEx("SMGPickup", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
            }    
        Stop;
    }
}

/*Actor SMGPickup : Custominventory
{
    Inventory.PickupSound "Weapon/Riflecock"
	Inventory.Pickupmessage "[2] - \c[\Yellow]Sub-machinegun\c- acquired."
	Scale 0.75
	States
	{
		Spawn:
			UZII A -1
			Stop	
		Pickup:
			TNT1 A 0
				{
				A_Giveinventory("Uzitoken",1);
				A_Giveinventory("JustaSMG",1);
				A_Takeinventory("Justamachinepistol",1);
				}
			Stop
	}
}*/

class JustaSMG : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "Smgmag";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "Bullets";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 20;
		Weapon.slotnumber 2;
		Weapon.SelectionOrder 1500;
		Weapon.SlotPriority 50;
		Obituary "%k Was picked off from a distance.";
		Weapon.UpSound "Weapon/Select";
		Inventory.PickupSound "Weapon/Riflecock";
		Inventory.Pickupmessage "[2] - \c[Yellow]Sub-machinegun\c- acquired.";
		Tag "$PC_SMGTAG";
		Inventory.AltHUDIcon "UZIIA0";
		-Weapon.noautofire;
		Scale 0.75;
		JustaWeapon.BarGraphic "PBullBar";
		JustaWeapon.CaseGraphic "PBullet";
	}
	
	action void PC_FireSMG(double spreadMod = 1.0) {
		A_AlertMonsters();
		PC_PlayPowerModSounds();
		A_startsound("MPistol/fire",10, CHANF_OVERLAP);
		PC_FireBullets("PC_PistolProjectile", 1, 2.5 * spreadMod, 0, 0, 2.5 * spreadMod, "SMGMag", 1, true);
		A_GunFlash();
		PC_GunSmoke(0,3,3);
		A_FireProjectile("PCspawner",0,0,2,10);
		A_ZoomFactor(0.99,ZOOM_INSTANT);
		PC_QuakeCamera(2,1);
	}
	
	States
	{
		Spawn:
			UZII A -1;
			Stop;
		Select:
			UZIM BA 1 A_WeaponReady(WRF_NOFIRE);
			UZIF E 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			UZIF E 1;
			UZIM AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			UZIF E 2 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Dryfire:
			UZIF E 16 A_startsound("Weapons/SMGempty",11,0);
			UZIF E 4;
			Goto ready;
		Fire:
			TNT1 A 0 A_JumpIfInventory("SMGmag",1,1);
			Goto Dryfire;
			UZIF A 1 Bright PC_FireSMG();
			UZIF B 1 Bright A_ZoomFactor(0.999);
			UZIF C 1 {
				A_ZoomFactor(1.0);
				PC_WeaponRecoil(2,2);
			}
			UZIF D 1;
			TNT1 A 0 A_ReFire("Hold");
			UZIF DE 1;
			Goto ready;
		  Hold:
			TNT1 A 0 A_JumpIfInventory("SMGmag",1,1);
			Goto Dryfire;
			UZIF A 1 Bright PC_FireSMG(1.8);
			UZIF B 1 Bright A_ZoomFactor(0.999);
			UZIF C 1 {
				A_ZoomFactor(1.0);
				PC_WeaponRecoil(2,2);
			}
			UZIF D 1;
			TNT1 A 0 A_ReFire("Hold");
			UZIF DE 1;
			Goto ready;
		Flash:
			TNT1 A 2 A_Light2;
			TNT1 A 2 A_Light1;
			Goto LightDone;
		Reload:
			TNT1 A 0 A_JumpIfInventory("SMGmag", 50, 2);
			TNT1 A 0 A_JumpIfInventory("Bullets", 1, "ReloadWork");
			UZIF E 1;
			Goto ready;
		Reloadwork:
			UZIF E 1;
			UZIR ABCD 1;
			TNT1 A 0 A_startsound("weapon/Rmagout",9,0);
			UZIR E 1 A_FireProjectile("Rclipspawner",0,0,0,-10);
			UZIR FGHI 1;
			UZIR I 5;
			UZIR J 2;
			UZIR K 1;
			UZIR L 2;
			UZIR M 5;
			TNT1 A 0 PC_AmmoIntoMag();
			UZIR N 2 A_startsound("weapon/Rmagin",11,0);
			UZIR OPQR 1;
			UZIR S 3;
			TNT1 A 0 A_startsound("Pistol/cock",12,0);
			UZIR TUVWXYZ 1;
			TNT1 A 0 A_startsound("Pistol/release",7);
			UZIR BA 1;
			UZIF E 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Goto Ready;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			UZIF E 1;
			UZIM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			UZIF E 1;
			UZIM AB 1;
			Goto Minethrow;
		Returnstate:
			UZIM BA 1;
			UZIF E 1;
			Goto Ready;
		}
	}