//phase Devil
$random Phasedevil/see {PDevilSee1 PDevilSee2}
PDevilSee1					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_Sight1.ogg
PDevilSee2					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_Sight2.ogg
$random PhaseDevil/Active {PDevil/Act1 PDevil/Act2}
PDevil/Act1					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_Act1.ogg
PDevil/Act2					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_Act2.ogg
$random PhaseDevil/Pain {PDevil/Pain1 PDevil/pain2}
PDevil/pain1					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_pain1.ogg
PDevil/pain2					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_pain2.ogg
$random Phasedevil/death {PDevilDie1 PDevilDie2}
PDevilDie1					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_Death1.ogg
PDevilDie2					Sounds/Enemies/Addons/CL/PhaseDevil/Phase_Devil_Death2.ogg

//Phase anni imps
$random Phaseanni/See			{PASee1 PASee2}
PAsee1							Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_Sight1.ogg
PAsee2							Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_Sight1.ogg
$Random Phaseanni/Die			{PAdie1  PAdie2}
PAdie1							Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_Death1.ogg
PAdie2							Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_Death1.ogg

$Random Phaseanni/Active	{Panni/Act1 Panni/Act2}
Panni/Act1					Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_act1.ogg
Panni/Act2					Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_act2.ogg
$random  Phaseanni/Pain	{Panni/Pain1 Panni/pain2}
Panni/pain1					Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_Pain1.ogg
Panni/pain2					Sounds/Enemies/Addons/CL/PhaseAI/Phase_Anni_Imp_Pain2.ogg

//Phase Brute
Phasebrute/See			Sounds/Enemies/Addons/CL/Brute/Phase_Brute_Sight_Sound.ogg
Phasebrute/Pain			Sounds/Enemies/Addons/CL/Brute/Phase_Brute_Pain_Sound.ogg
Phasebrute/Act				Sounds/Enemies/Addons/CL/Brute/Phase_Brute_Active_sound.ogg
Phasebrute/die				Sounds/Enemies/Addons/CL/Brute/Phase_Brute_Death_sound.ogg

Phasebrute/Bite			Sounds/Enemies/Addons/CL/Brute/Phase_Brute_Bite_Sound.ogg
Phasebrute/charge		Sounds/Enemies/Addons/CL/Brute/Phase_Brute_Charge_Sound.ogg
Phasebrute/Wall			Sounds/Enemies/Addons/CL/Brute/Phase_Brute_Wall_hit_Sound.ogg


//Phase noble
Phasenoble/darkmatter		Sounds/Enemies/Addons/CL/Phasenoble/Phase_noble_darkmatter.ogg
Phasenoble/death				Sounds/Enemies/Addons/CL/Phasenoble/Phase_Noble_Death_Sound.ogg

$random Phasenoble/See {PNSee1 PNSee2}
PNSee1								Sounds/Enemies/Addons/CL/Phasenoble/Phase_Noble_Sight1.ogg
PNSee2								Sounds/Enemies/Addons/CL/Phasenoble/Phase_Noble_Sight2.ogg
$Random Phasenoble/active {PNact1 PNact2}
PNAct1								Sounds/Enemies/Addons/CL/Phasenoble/Phase_Noble_Active1.ogg
PNAct2								Sounds/Enemies/Addons/CL/Phasenoble/Phase_Noble_Active2.ogg
$random Phasenoble/pain {PNPain1 PNPain2}
PNpain1							Sounds/Enemies/Addons/CL/Phasenoble/Phase_Noble_Pain1.ogg
PNpain2							Sounds/Enemies/Addons/CL/Phasenoble/Phase_Noble_Pain1.ogg

//Poes
Phasepoe/See					Sounds/Enemies/Addons/CL/Poes/Phase_Poe_Sight_Sound.ogg
Phasepoe/Active				Sounds/Enemies/Addons/CL/Poes/Phase_Poe_Active_sound.ogg
Phasepoe/Pain					Sounds/Enemies/Addons/CL/Poes/Phase_poe_Pain_Sound.ogg
Phasepoe/Die					Sounds/Enemies/Addons/CL/Poes/Phase_Poe_Death_Sound.ogg
Phasepoe/Melee				Sounds/Enemies/Addons/CL/Poes/Phase_Poe_Bite_Sound.ogg

Shadowpoe/See				Sounds/Enemies/Addons/CL/Poes/Shadow_Poe_Sight_Sound.ogg
Shadowpoe/Active			Sounds/Enemies/Addons/CL/Poes/Shadow_Poe_Active-Sound.ogg
Shadowpoe/Pain				Sounds/Enemies/Addons/CL/Poes/Shadow_Poe_pain_Sound.ogg
Shadowpoe/Die				Sounds/Enemies/Addons/CL/Poes/Shadow_Poe_Death_Sound.ogg
Shadowpoe/Melee				Sounds/Enemies/Addons/CL/Poes/Shadow_Poe_Bite_Sound.ogg


//Tormentor
Phasetormentor/Litecharge					Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Light_Charging.ogg
Phasetormentor/Liteshot						Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Lightning_shot.ogg
Phasetormentor/Liteexp						Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Light_Shot_exp.ogg

$rolloff Phasetormentor/Liteshot 800 2100
$rolloff Phasetormentor/Liteexp	 800 2100


Phasetormentor/Darkmatter					Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Darkmatter.ogg
Phasetormentor/Lightningstorm			Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Lightning_storm.ogg

Phasetormentor/See								Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Sight.ogg
Phasetormentor/act								Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Active.ogg
Phasetormentor/pain							Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Pain_Sound.ogg
Phasetormentor/death							Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Death_Sound.ogg

Phasetormentor/Soulspit						Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Soul_Spit.ogg
Phasetormentor/elementalsummon		Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_Elemental_Spit.ogg
Phasetormentor/explosion					Sounds/Enemies/Addons/CL/Tormentor/Phase_Tormentor_explode.ogg