class PC_Fuel : Ammo replaces ID24Fuel
{
	Default
	{
		Inventory.PickupMessage "$ID24_GOTFUELCAN";
		Inventory.Amount 10;
		Inventory.MaxAmount 150;
		Ammo.BackpackAmount 10;
		Ammo.BackpackMaxAmount 300;
		Inventory.Icon "FTNKA0";
		Tag "$AMMO_ID24FUEL";
	}
	States
	{
	Spawn:
		FCPU A -1;
		Stop;
	}
}

class PC_FuelTank : PC_Fuel replaces ID24FuelTank
{
	Default
	{
		Inventory.PickupMessage "$ID24_GOTFUELTANK";
		Inventory.Amount 50;
		Ammo.DropAmmoFactorMultiplier 0.8; // tank has 20 drop amount, not 25, so multiply the factor by a further 0.8
										   // -- for custom dehacked ammo this can be calculated based on the drop amount and the default factor
		Tag "$AMMO_ID24FUELTANK";
	}
	States
	{
	Spawn:
		FTNK A -1;
		Stop;
	}
}