/*
//Ammo
Actor Ammobaconitem : CustomInventory
{
Height 10
Radius 10
+COUNTITEM
+INVENTORY.INVBAR
Inventory.Amount 1
Inventory.MaxAmount 3
Inventory.Icon "AEACB0"
 Inventory.PickupSound "Beacon/Pickup"
Inventory.PickupMessage "UAC-Brand 'need more ammo? Have some more ammo, friend', \c[Backpackcolor]Ammo Beacon\c- (Provides ammo backpacks)"
Tag "$AmmoB"
States
	{
	Spawn:
		AEAC A -1
		Loop
	Use:
		TNT1 A 0
		TNT1 A 0 A_JumpIf(waterlevel > 2,"Nope")
		TNT1 A 0 A_playsound("Beacon/place",7)
		TNT1 A 1 A_SpawnItemEx("Ammobeacon",0,0,8,0,0,0,0,SXF_NOCHECKPOSITION,0)
		Stop
	 Nope:
		TNT1 A 0 
		Fail
	}
}

Actor Beaconcooldown : PowerDamage
{
DamageFactor "nothing", 1.0
Powerup.duration -20
}

Actor Ammobeacon
{
Height 30
Radius 20
Speed 0
-COUNTKILL
-SOLID
+NODAMAGE
+SEEINVISIBLE
+NOTARGET
+NOBLOOD
+DONTHARMSPECIES
mass 0x7fffffff
Species "Player"
Tag "Beacon ammunition supply"
Var int User_Usage;
States
	{
	Spawn:
		AEAC A 35
	Idle:
		TNT1 A 0 A_ChangeFlag(FRIENDLY,0)
		TNT1 A 0 A_ChangeFlag(NOBLOCKMAP,0)
		TNT1 A 0 A_SetTranslucent(1,0)
		TNT1 A 0 A_LookEx(LOF_NOSOUNDCHECK|LOF_NOSEESOUND,0,100,0,360,"Supply")
		TNT1 A 0 A_ChangeFlag(FRIENDLY,1)
		AEAC A 10 
		Loop
	Supply:
		TNT1 A 0 A_JumpIf(user_Usage==3,"shutdown")
	Actuallysupplystuff:
		TNT1 A 0 A_ChangeFlag(FRIENDLY,1)
		TNT1 A 0 A_JumpIfInTargetInventory("Beaconcooldown",1,"Noway")
		TNT1 A 0 A_GiveToTarget("Beaconcooldown",1)
		TNT1 A 0 A_SpawnItemEx ("TeleportFog",0,0,8,0,0,0,0,SXF_NOCHECKPOSITION,0)
		AEAC A 35 Bright A_SpawnItemEx("Ammosupply",random(-10,10),random(-10,10),0,0,0,0,0,SXF_NOCHECKPOSITION,0)
		AEAC A 35
		Goto cooldown
	cooldown:
		TNT1 A 0 A_PlaySound("Beacon/no")
		AEAC AAA 35 
		AEAC A 35 bright Light("ABeacon") a_playsound("Items/beep",5,0.4)
		AEAC AAA 35
		AEAC A 35 bright Light("ABeacon") a_playsound("Items/beep",5,0.4)
		AEAC AAA 35		
		AEAC A 35 bright Light("ABeacon") a_playsound("Items/beep",5,0.4)
		AEAC AAA 35
		AEAC A 35 bright Light("ABeacon") a_playsound("Items/beep",5,0.4)
		AEAC AAA 35
		AEAC A 35 bright Light("ABeacon") a_playsound("Items/beep",5,0.4)
		AEAC AAA 35
		AEAC A 35 bright Light("ABeacon") a_playsound("Items/beep",5,0.4)
		AEAC AAA 35
		AEAC A 35 bright Light("ABeacon") a_playsound("Items/beep",5,0.4)
		AEAC AA 35
		TNT1 A 0 A_SetUserVar("user_Usage",user_Usage+1)
		Goto Idle
	Shutdown:
		TNT1 A 0 A_die
	death:
		AEAC A 105 Bright Light("Zombierail") A_playsound("Dispenser/PDown",7)
		TNT1 A 0 A_playsound("world/barrelx",7)
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode")
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128) 
		TNT1 AAA 0 a_custommissile("SmallKaboom", 0, 0, random(0,360), 2, random(0,360))
		TNT1 AAAAAAAA 0 A_SpawnItemEx("MineExSpark",0,0,10,FRandom(6,-6),FRandom(6,-6),FRandom(8,12))
		TNT1 A 1 A_SpawnItemEx("MineEx",0,0,0,0,0,0,0,128)
		TNT1 A 0 Radius_quake(3,8,0,10,0)
		TNT1 A 0 Radius_Quake(1,8,0,28,0)
		TNT1 AAAA 0 
			{
			A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			}
		TNT1 AAAAA 5 A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0)
		TNT1 A 0 A_die
		TNT1 A -1 a_noblocking
		stop
	LessExplode:
		TNT1 A 0 A_playsound("world/barrelx",7)
		TNT1 A 1 A_SpawnItemEx("MineEx",0,0,0,0,0,0,0,128)
		TNT1 A 0 Radius_quake(3,8,0,10,0)
		TNT1 A 0 Radius_Quake(1,8,0,28,0)
		TNT1 A -1 a_noblocking
		stop
	}
}
*/

//Marine beacon
Class Baconitem : CustomInventory
{
	Default
	{
		+INVENTORY.INVBAR;
		Inventory.MaxAmount 3;
		Inventory.Icon "BEACZ0";
		Inventory.PickupSound "Beacon/Pickup";
		Inventory.PickupMessage "Picked up a UAC-brand 'It's gank-city now, boyos' \c[darkgray]Summon Beacon\c- (Summons Marine allies)";
		Tag "$Beacon";
	}
		
	States
	{
		Spawn:
			BEAC A -1;
			Stop;
		Use:
			TNT1 A 1 
			{
				let bacon = ActiveBeacon(Spawn('ActiveBeacon', invoker.Owner.Pos));
				bacon.Master = invoker.Owner;
				//A_SpawnItemEx("ActiveBeacon", 56, 0, 8, 0, 0, 0, 0, 1);
				
				A_startsound("Beacon/place",0);
			}
			Stop;
	}
}

class ActiveBeacon : Actor
{
	Default
	{
		-SOLID;
		-SHOOTABLE;
		+FRIENDLY;
		-COUNTKILL;
	}
	
	action void PC_BeaconSpawnMarines()
	{
		//[Pop] NOTE, this needs to be changed later to a dynamic array
		//thats built by checking for every actor that inherits from Friendly_Marine
		//then doing a random based on the size of that array, or just randomly
		//picking from that array
		
		Spawn("TeleportFog", Pos);
		
		Actor Marine;
		
		switch(random(1,10))
		{
			default:
			case 1:
				Marine = PCShotgunmarine(Spawn("PCShotgunmarine", Pos));
				break;
			case 2:
				Marine = PCAssaultRiflemarine(Spawn("PCAssaultRiflemarine", Pos));
				break;
			case 3:
				Marine = PCAssaultShotgunmarine(Spawn("PCAssaultShotgunmarine", Pos));
				break;
			case 4:
				Marine = PCDTechRiflemarine(Spawn("PCDTechRiflemarine", Pos));
				break;
			case 5:
				Marine = PCMinigunmarine(Spawn("PCMinigunmarine", Pos));
				break;
			case 6:
				Marine = PCPlasmamarine(Spawn("PCPlasmamarine", Pos));
				break;
			case 7:
				Marine = PCQSGmarine(Spawn("PCQSGmarine", Pos));
				break;
			case 8:
				Marine = PCSSGmarine(Spawn("PCSSGmarine", Pos));
				break;
			case 9:
				Marine = PCRocketmarine(Spawn("PCRocketmarine", Pos));
				break;
			case 10:
				Marine = PCRailgunmarine(Spawn("PCRailgunmarine", Pos));
				break;
		}
		Marine.Master = self.Master;
		Marine.Target = self.Master;
	}
			
	States
	{
		Spawn:
			BEAC A 105;
			BEAC A 105 PC_BeaconSpawnMarines();
			BEAC A 105 PC_BeaconSpawnMarines();
			BEAC A 105 PC_BeaconSpawnMarines();
			goto Death;
		Death:
			TNT1 A 1 A_CustomMissile("TeleportFog", 0, 0, 0, 0, 0);
			stop;
	}
}