class Eminiguntoken : Inventory{ Default { Inventory.maxamount 1; }}

class EminnyDrop : Actor
{
	Default
	{
		+FLOORCLIP
	}
States
    {
    Spawn:
        TNT1 A 0 Nodelay
            {
                If (ACS_NamedExecuteWithResult("WeaponSwap",4) ==2)
                {
                  A_SpawnItemEx("Beltbox", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
                Else
                  {
                  A_SpawnItemEx("EminnyPickup", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
            }    
        Stop;
    }
}


/*
Actor EminnyPickup : Custominventory
{
    Inventory.PickupSound "Weapon/Riflecock"
	Inventory.Pickupmessage "[4] - \c[\BrighterYellow]Explosive Rotary cannon\c- acquired."
	-INVENTORY.ALWAYSPICKUP
	States
	{
		spawn:
			RMN2 A -1
			Stop
		Pickup:
			TNT1 A 0 A_jumpifinventory("PC_ExplosiveBullets",0,"Nopickup")
			TNT1 A 0
				{
				A_Giveinventory("Eminiguntoken",1);
				A_Giveinventory("JustaHMG",1);
				A_Takeinventory("Justaminnygun",1);
				}
			Stop
		Nopickup:
			TNT1 A 0
			Fail
	}
}*/

class JustaHMG : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "PC_ExplosiveBullets";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 75;
		Weapon.slotnumber 5;
		Weapon.SelectionOrder 600;
		Weapon.SlotPriority 40;
		Weapon.UpSound "Weapon/Select";
		Inventory.PickupSound "Weapon/Riflecock";
		Inventory.Pickupmessage "[4] - \c[Explosiveyellow]Explosive Rotary cannon\c- acquired.";
		Tag "$PC_EXPLOSIVEMGTAG";
		Inventory.AltHUDIcon "RMN2A0";
		-Weapon.noautofire;
		JustaWeapon.BarGraphic "XBullBar";
		JustaWeapon.CaseGraphic "XBullet";
	}
	
	action void PC_FireHMG() {
		A_startsound("monsters/DarkMMGfire",10,0,0.95);
		PC_PlayPowerModSounds();
		PC_FireBullets("PC_HMGProjectile", 3.7, 2.7);
		PC_TakeAmmo("PC_ExplosiveBullets");
		A_GunFlash();
		PC_GunSmoke(0,3,4);
	}
	
	action void PC_FireHMGAlt() {
		A_AlertMonsters();
		A_GunFlash();
		PC_QuakeCamera(2,2);
		PC_PlayPowerModSounds();
		A_startsound("Weapons/Cannonfire",10);
		PC_FireBullets("PC_HMGAltProjectile", 1.5, 1.5);
		PC_TakeAmmo("PC_ExplosiveBullets", 50);
		PC_GunSmoke(0,3,4);
	}
	
	States
		{
		spawn:
			RMN2 A -1;
			Stop;
		Select:
			RMNM BA 1 A_WeaponReady(WRF_NOFIRE);
			RMNG F 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			RMNG F 1;
			RMNM AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			RMNG F 1 A_WeaponReady(WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Dryspin:
			TNT1 A 0 A_ClearReFire();
			TNT1 A 0 
				{
				A_stopsound(10);
				A_stopsound(11);
				}
			RMNG CDEF 1;
			RMNG C 1;
			RMNG D 1 A_startsound("Weapons/Minnyempty",11,0);
			RMNG E 2;
			RMNG F 3;
			Goto Ready;
		Fire:
			TNT1 A 0 A_Jumpifinventory("PC_ExplosiveBullets",1,1);
			Goto dryspin;
			RMNG C 3 A_startsound("EHMG/Spinup",12,0,0.35);
			RMNG DEF 2;
			RMNG C 1 A_Refire("Hold");
			RMNG D 1 A_StopSound(12);
			TNT1 A 0 A_startsound("EHMG/Spindown",13,0,0.45);
			RMNG EFC 2;
			RMNG D 3;
			Goto Ready;
		Hold:
			TNT1 A 0 A_startsound("EHMG/Spinning",11,CHANF_LOOPING,0.6);
		Attackloop:
			TNT1 A 0 A_JumpIfInventory("PC_ExplosiveBullets",1,1);
			Goto Dryspin;
			RMNG B 1 Bright PC_FireHMG();
			RMNG G 1 {
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_QuakeCamera(2,2);
				A_FireProjectile("RCSpawner3",0,0,2,-3);
				A_FireProjectile("Linkspawner2",0,0,2,-3);
				PC_WeaponRecoil(1,1);
			}
			RMNG H 1 A_ZoomFactor(0.999);
			RMNG I 1 A_ZoomFactor(1.0);
			TNT1 A 0 A_ReFire("Attackloop");
			TNT1 A 0 
				{
				A_stopsound(10);
				A_StopSound(11);
				A_stopsound(12);
				A_ClearReFire();
				}
			TNT1 A 0 A_startsound("EHMG/Spindown",13,0,0.45);
		Endone:
			RMNG FCDEF 1;
			RMNG CDE 2;
			RMNG F 3;
			Goto Ready;
		Altfire:
			TNT1 A 0 A_jumpifinventory("PC_ExplosiveBullets",50,1);
			Goto Dryspin;
			RMNG F 1;
			RMNG A 2 BRIGHT PC_FireHMGAlt();
			RMNG G 1 {
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_WeaponRecoil(5, 5);
			}
			RMNG H 1 A_ZoomFactor(0.999);
			RMNG I 1 A_ZoomFactor(1.0);
			RMNG F 30;
			TNT1 A 0 A_startsound("Weapons/CannonBuzz",15);
			RMNG F 20;
			RMNG FFFFFFFFFF 1
				{
				A_FireProjectile("RCSpawner3",0,0,2,-3);
				A_FireProjectile("Linkspawner2",0,0,2,-3);
				}
			TNT1 A 0 A_startsound("Weapons/Cannonspin",17);
			RMNG CDEF 1;
			RMNG C 2;
			RMNG D 3;
			RMNG E 4;
			Goto Ready;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			RMNM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			RMNM AB 1;
			Goto Minethrow;
		Returnstate:
			RMNM BA 1;
			RMNG F 1;
			Goto Ready;
	}
}