class MinnySpawner : Actor
{
	Default
	{
		+FLOORCLIP;
	}
States
    {
    Spawn:
        TNT1 A 0 Nodelay
            {
                If (ACS_NamedExecuteWithResult("WeaponSwap",4) ==2)
                {
                  A_SpawnItemEx("Beltbox", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
                Else
                  {
                  A_SpawnItemEx("Justaminnygun", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
            }    
        Stop;
    }
}

class MapMinnyspawner : Actor
{
	Default
	{
		+FLOORCLIP;
	}
States
    {
    Spawn:
        TNT1 A 0 Nodelay
            {
                If (ACS_NamedExecuteWithResult("WeaponSwap",4) ==2)
                {
                  A_SpawnItemEx("Beltbox", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
                Else
                  {
                  A_SpawnItemEx("JAMGSpawner", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
            }    
        Stop;
    }
}


class Justaminnygun : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "Heavybullets";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 100;
		Weapon.slotnumber 5;
		Weapon.SelectionOrder 600;
		Weapon.SlotPriority 20;
		Inventory.PickupSound "Weapon/Riflecock";
		Inventory.AltHUDIcon "MGUNA0";
		Inventory.Pickupmessage "[4] - \c[BrighterYellow]Rotary cannon\c- acquired.";
		Tag "$PC_MINIGUNTAG";
		-Weapon.noautofire;
		JustaWeapon.BarGraphic "BulltBar";
		JustaWeapon.CaseGraphic "Bullet";
	}
	
	action void PC_FireMinigun() {
		A_AlertMonsters();
		A_StartSound("weapons/minigunfire", 10);
		PC_PlayPowerModSounds();
		A_GunFlash();
		PC_FireBullets("PC_MinigunProjectile", 4.3, 2.6);
		PC_TakeAmmo("HeavyBullets");
		PC_GunSmoke(0,3,4);
	}
	
	States
	{
		spawn:
			MGUN A -1;
			Stop;
		Select:
			MGUM BA 1 A_WeaponReady(WRF_NOFIRE);
			CHAG A 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			TNT1 A 0 
				{
				A_stopsound(10);
				A_Stopsound(12);
				}
			CHAG A 1;
			MGUM AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			CHAG A 1 A_WeaponReady(WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Dryspin:
			TNT1 A 0 A_Clearrefire();
			TNT1 A 0 
				{
				A_stopsound(10);
				A_Stopsound(12);
				}
			CHAG ABCD 1;
			CHAG A 1;
			CHAG B 1 A_startsound("Weapons/Minnyempty",11,0);
			CHAG C 2;
			CHAG D 3;
			Goto Ready;
		Fire:
			TNT1 A 0 A_Jumpifinventory("Heavybullets",1,1);
			Goto dryspin;
			CHAG B 2 A_startsound("weapons/mgunspinstart",12,0);
			CHAG C 2;
			CHAG DABC 1;
			TNT1 A 0 A_Refire();
			Goto Endone;
		Hold:
			TNT1 A 0 A_Jumpifinventory("Heavybullets",1,1);
			Goto dryspin;
			TNT1 A 0 A_startsound("weapons/mgunspin",12,CHANF_Looping,1);
		Attackloop:
			CHAF A 1 Bright PC_FireMinigun();
			CHAF B 1 {
				A_FireProjectile("RCSpawner2",0,0,2,-3);
				A_FireProjectile("Linkspawner",0,0,2,-3);
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_QuakeCamera(2,2);
				PC_WeaponRecoil(0.75,0.5);
			}
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				if(CountInv("HeavyBullets") < 1) return resolvestate("DrySpin");
				return resolvestate(null);
			}
			CHAF C 1 Bright PC_FireMinigun();
			CHAF D 1 {
				A_FireProjectile("RCSpawner2",0,0,2,-3);
				A_FireProjectile("Linkspawner",0,0,2,-3);
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_QuakeCamera(2,2);
				PC_WeaponRecoil(0.75,0.5);
			}
			TNT1 A 0 {
				A_ZoomFactor(1.0);
				if(CountInv("HeavyBullets") < 1) return resolvestate("DrySpin");
				return resolvestate(null);
			}
			TNT1 A 0 A_Refire("Attackloop");
		Endone:
			TNT1 A 0 {
				A_stopsound(10);
				A_StopSound(12);
				A_startsound("weapons/mgunspinstop",13,0,0.5);
				A_clearrefire();
			}
			CHAG ABCD 1;
			CHAG ABCD 2;
			Goto Ready;
		Flash:
			TNT1 A 2 A_Light2;
			TNT1 A 2 A_Light1;
			Goto LightDone;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			CHAG A 1;
			MGUM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			CHAG A 1;
			MGUM AB 1;
			Goto Minethrow;
		Returnstate:
			MGUM BA 1;
			CHAG A 1;
			Goto Ready;
	}
}
		