class Boomtube : Ammo
{
	Default
	{
		Inventory.Amount 0;
		Inventory.MaxAmount 10;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 10;
		Inventory.Icon "XSHELLS";
		+INVENTORY.IGNORESKILL;
	}
}

class ESGSpawner : Actor
{
	Default
	{
		+FLOORCLIP;
	}
States
    {
    Spawn:
        TNT1 A 0 Nodelay
            {
                If (ACS_NamedExecuteWithResult("WeaponSwap",5) ==2)
                {
                  A_SpawnItemEx("Eshellbox", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
                Else
                  {
                  A_SpawnItemEx("JustaESG", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
            }    
        Stop;
    }
}

class JustaESG : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "Boomtube";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "EShells";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 10;
		Weapon.SelectionOrder 400;
		Weapon.Slotnumber 3;
		Weapon.SlotPriority 10;
		Scale 0.9;
		Obituary "%o was made extra crispy by Explosive pellets.";
		Weapon.UpSound "Weapon/Select";
		Inventory.PickupSound "Weapons/PUMPB";
		Inventory.Pickupmessage "[3] - \c[Explosiveorange]Explosive shotgun\c- acquired.";
		Tag "$PC_EXPLOSIVESHOTGUNTAG";
		Inventory.AltHUDIcon "M87PA0";
	}
	States
		{
		spawn:
			M87P A -1;
			Stop;
		Select:
			M87M BA 1 A_WeaponReady(WRF_NOFIRE);
			M87G A 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			M87G A 1;
			M87M AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			M87G A 1 A_WeaponReady(WRF_ALLOWZOOM|WRF_ALLOWRELOAD|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Dryfire:
			M87G A 16 A_startsound("Weapons/ShotgunEempty",11);
			M87G A 4;
			Goto ready;
		Fire:
			TNT1 A 0 A_Jumpifinventory("Boomtube",1,1);
			Goto Dryfire;
			TNT1 A 0 
				{
				A_AlertMonsters();
					If(CountInv("Power4xDamage"))
					{
						A_startsound("Weapons/quadfire",5);
					}
					If(CountInv("Chalicedamage"))
					{
						A_startsound("Weapons/quadfire",5);
					}
				 A_startsound("Weapons/ESGfire",10,0,1);
				A_GunFlash();
				}
			M87F A 2 BRIGHT A_FireBullets(7, 7, 8, 20, "ESGpuff",FBF_NORANDOM);
			TNT1 A 0 
				 {
				  if(CountInv("Guntoken") && random(1,5) == 5)
					{
					A_FireBullets(10, 10, 8, 20, "ESGpuff",FBF_NORANDOM);
					A_startsound("Gun/Proc",999,0,1);
					}
				  }
			TNT1 A 0 PC_QuakeCamera(2,4); //Radius_Quake(3,3,0,1,0)
			TNT1 A 0 A_ZoomFactor(0.99,ZOOM_INSTANT);
			TNT1 A 0 A_JumpIf(GetCvar("Spooks_Norecoil")==1, "Followthrough");
			TNT1 A 0 PC_WeaponRecoil(7,7);
		Followthrough:
			M87F B 2 BRIGHT;
			M87F C 1 Offset(0,34);
			TNT1 A 0 A_FireCustomMissile("GSSpawner2",0,0,0,4);
			M87F DE 1 Offset(0,36);
			TNT1 A 0 A_ZoomFactor(0.999);
			M87G A 1 Offset(0,37);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_Jump(128,2);
			TNT1 A 0 A_Jump(128,2);
			M87G A 1 Offset(0,35);
			M87G A 1 Offset(0,34);
			M87G BBCCDDEEFG 1;
			M87G H 1 A_startsound("Weapons/Leverdown",12);
			M87G IJ 1;
			TNT1 A 0 A_FireCustomMissile("LGSSpawner",-40,0,-8,-26);
			TNT1 A 0 
				 {
					if(CountInv("Ammotoken") && random(1,5) == 5) 
					{
					A_startsound("ammo/Proc",999,0,0.65);
					}
				else
					{
					A_takeinventory("Boomtube",1,TIF_NOTAKEINFINITE); 
					}
				}
			M87G IH 1;
			TNT1 A 0 A_startsound("Weapons/leverup",13);
			M87G GFEEDDCCBB 1;
			Goto ready;
		Reload:
			TNT1 A 0 A_JumpIfInventory("Boomtube", 10, 2);
			TNT1 A 0 A_JumpIfInventory("EShells", 1, "Properreload");
			M87G A 1;
			Goto Ready;
		Properreload:
			TNT1 A 0 A_JumpIfInventory("Boomtube",1,"Properreload2");
			M8RS ABC 1;
			M8RS C 4;
		Reloadloop:
			M87R A 3;
			M87R BC 1;
			TNT1 A 0
				{
				A_startsound("Weapons/ExShellsert",9);
				A_TakeInventory("EShells",1);
				A_GiveInventory("Boomtube",1);
				}
			M87R EFGHIJKL 1 A_WeaponReady(WRF_NOBOB|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			M8RS C 8;
			TNT1 A 0 A_JumpIfInventory("Boomtube",10,"ReloadFinish");
			TNT1 A 0 A_JumpIfInventory("EShells",1,"Reloadloop");
			Goto ReloadFinish;
		Reloadfinish:
			M8RS CBA 1;
			M87G A 1;
			M87G BBCCDDEEFG 1;
			M87G H 1 A_startsound("Weapons/leverdown",12);
			M87G IJ 1;
			M87G IH 1;
			TNT1 A 0 A_startsound("Weapons/leverup",18);
			M87G GFEEDDCCBB 1;
			Goto ready;
		Properreload2:
			M8RS ABC 1;
			M8RS C 4;
		Reloadloop2:
			M87R A 3;
			M87R BC 1;
			TNT1 A 0
				{
				A_startsound("Weapons/ExShellsert",9);
				A_TakeInventory("EShells",1);
				A_GiveInventory("Boomtube",1);
				}
			M87R EFGHIJKL 1 A_WeaponReady(WRF_NOBOB|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			M8RS C 8;
			TNT1 A 0 A_JumpIfInventory("Boomtube",10,"ReloadFinish2");
			TNT1 A 0 A_JumpIfInventory("EShells",1,"Reloadloop2");
			Goto ReloadFinish2;
		Reloadfinish2:
			M8RS CBA 1;
			M87G A 1;
			Goto ready;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			M87G A 1;
			M87M AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			M87G A 1;
			M87M AB 1;
			Goto Minethrow;
		Returnstate:
			M87M BA 1;
			M87G A 1;
			Goto Ready;
	}
}