class Boomtube2 : Ammo
{
	Default
	{
		Inventory.Amount 0;
		Inventory.MaxAmount 2;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 2;
		Inventory.Icon "XSHELLS";
		+INVENTORY.IGNORESKILL;
	}
}

class JustaESOG : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "Boomtube2";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "EShells";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 10;
		Weapon.SelectionOrder 500;
		Weapon.Slotnumber 3;
		Weapon.SlotPriority 70;
		Scale 0.9;
		Obituary "%o was made extra crispy by Explosive pellets.";
		Weapon.UpSound "Weapon/Select";
		Inventory.PickupSound "Weapons/PUMPB";
		Inventory.Pickupmessage "[3] - \c[Explosiveorange]Explosive sawed-off shotgun\c- acquired.";
		Tag "$PC_EXPLOSIVESSGTAG";
		Inventory.AltHUDIcon "XGN2A0";
		JustaWeapon.BarGraphic "XShelBar";
		JustaWeapon.CaseGraphic "XShell";
	}
	
	action void PC_FireExSSG(bool both = true) {
		A_AlertMonsters();
		PC_PlayPowerModSounds();
		A_GunFlash();
		if(both) {
			A_startsound("Weapons/EXSOFire",10,0,1);
			PC_FireBullets("PC_ExSGProjectile", 14.0, 9.0, 16);
			PC_TakeAmmo("BoomTube2", 2);
			PC_GunSmoke(-1,3,3);
			PC_GunSmoke(1,3,3);
		}
		else {
			A_startsound("Weapons/EXSOTriggerPull",11);
			A_startsound("Weapons/EXSOAltfire",10,0,0.85);
			if(CountInv("BoomTube2") < 2) PC_SetFrame(1);
			PC_FireBullets("PC_ExSGProjectile", 7.0, 7.0, 8);
			PC_TakeAmmo("BoomTube2");
			PC_GunSmoke(0,3,3);
		}
	}
	
	States
		{
		spawn:
			XGN2 A -1;
			Stop;
		Select:
			XHTM BA 1 A_WeaponReady(WRF_NOFIRE);
			XHTZ A 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			XHTZ A 1;
			XHTM AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			XHTZ A 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Dryfire:
			XHTZ A 4 A_startsound("Weapons/MGSGEmpty");
			Goto Ready;
		Fire:
			TNT1 A 0 A_JumpIfInventory("Boomtube2",2,"FireBoth");
			TNT1 A 0 A_JumpIfInventory("Boomtube2",1,"Altfire");
			Goto dryfire;
		FireBoth:
			XHTP A 2 A_startsound("Weapons/EXSOTriggerPull",11);
			XHOF A 1 Bright PC_FireExSSG();
			XHOF B 1 Bright {
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_QuakeCamera(3,6);
				PC_WeaponRecoil(6,6);
			}
			XHOF C 1;
			XHOF D 1 A_ZoomFactor(0.999);
			XHOF E 1;
			XHOF F 1 A_ZoomFactor(1.0);
			XHOF GHI 1;
			Goto Ready;
		Altfire:
			TNT1 A 0 A_JumpIfInventory("Boomtube2",1,1);
			Goto dryfire;
			XHTU A 1 bright PC_FireExSSG(false);
			XHOF C 1 {
				PC_QuakeCamera(2,4);
				A_ZoomFactor(0.99, ZOOM_INSTANT);
				PC_WeaponRecoil(4,4);
			}
			XHOF D 1;
			XHOF E 1 A_ZoomFactor(0.999);
			XHOF F 1;
			XHOF G 1 A_ZoomFactor(1.0);
			XHOF HI 1;
			Goto Ready;
		Reload:
			TNT1 A 0 A_Jumpifinventory("Boomtube2",2,"Ready");
			TNT1 A 0 A_Jumpifinventory("Boomtube2",1,"Reloadright");
			TNT1 A 0 A_Jumpifinventory("EShells",1,"Doublereload");
			XHTZ A 1;
			Goto reloadright;
		Doublereload:
			//XHTZ BC 1 //[CHANGED]
			XHTZ BCDE 1;
			XHTZ F 1 A_startsound("Weapons/EXSawedopen",9,0);
			XHTZ GHIJK 1;
			TNT1 AA 0 A_FireProjectile("EXSSpawner",-6,0,-19,-20,-14);
			XHTZ L 20;
			XSGD ABCD 1;
			XSGD E 2;
			XSGD FGH 1;
			TNT1 A 0
				{
				A_startsound("Weapons/EXShellslide",11,0);
				PC_AmmoIntoMag(1, true);
				}			
			XSGD IIJKKLMNOOOPPQRS 1;
			TNT1 A 0
				{
				A_startsound("Weapons/EXShellslide",11,0);
				PC_AmmoIntoMag(1, true);
				}
			XSGD T 2;
			XSGD UVWX 1;
			TNT1 A 0 A_startsound("Weapons/EXSawedclose",11,0);
			XHTZ UVWX 1;
			XHTZ YZ 1;
			XHTZ EDCB 1;
			Goto Ready;
		Reloadright:
			TNT1 A 0 A_Jumpifinventory("EShells",1,2);
			XHT2 A 1;
			Goto Ready;
			//XHTZ BC 1 //[CHANGED]
			XHTZ BCDE 1;
			XHTZ F 1 A_startsound("Weapons/EXSawedopen",9,0);
			XHTZ GHIJK 1;
			TNT1 A 0 A_FireProjectile("EXSSpawner",-6,0,-19,-20,-14);
			XHT7 L 20;
			XSGD YZ 1;
			XXGD ABC 1;
			XSGD QRS 1;
			TNT1 A 0
				{
				A_startsound("Weapons/EXshellslide",11,0);
				PC_AmmoIntoMag(1, true);
				}
			XSGD T 2;
			XSGD UVWX 1;
			TNT1 A 0 A_startsound("Weapons/EXSawedclose",11,0);
			XHTZ UVWX 1;
			XHTZ YZ 1;
			XHTZ EDCB 1;
			Goto Ready;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			XHTZ A 1;
			XHTM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			XHTZ A 1;
			XHTM AB 1;
			Goto Minethrow;
		Returnstate:
			XHTM BA 1;
			XHTZ A 1;
			Goto Ready;
	}
}