class Quadtube : Ammo
{
	Default
	{
	  Inventory.Amount 0;
	  Inventory.MaxAmount 4;
	  Ammo.BackpackAmount 0;
	  Ammo.BackpackMaxAmount 4;
	  Inventory.Icon "SHELLS";
	  +INVENTORY.IGNORESKILL;
  }
}

class QSGToken : Inventory{ Default { Inventory.maxamount 1; }}

class QSGDrop : Actor
{
	Default
	{
		+FLOORCLIP;
	}
States
    {
    Spawn:
        TNT1 A 0 Nodelay
            {
                If (ACS_NamedExecuteWithResult("WeaponSwap",2) ==2)
                {
                  A_SpawnItemEx("BoxoShells", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
                Else
                  {
                  A_SpawnItemEx("QSGPickup", 0,0,0, 0,0,0, 0, SXF_NOCHECKPOSITION | SXF_TRANSFERSPECIAL, 0, tid);
                  }
            }    
        Stop;
    }
}
/*
Actor QSGPickup : Custominventory
{
    Inventory.PickupSound "weapons/shellslide"
	Inventory.Pickupmessage "[3] - \c[brighterOrange]Quad-barreled shotgun\c- acquired."
	-INVENTORY.ALWAYSPICKUP
	States
	{
		Spawn:
			QSG2 A -1
			Stop
		Pickup:
			TNT1 A 0
				{
				A_Giveinventory("QSGToken",1);
				A_Giveinventory("JustaQSG",1);
				A_Takeinventory("JustaSSG",1);
				}
			Stop
		Nopickup:
			TNT1 A 0
			Fail
	}
}
*/
class JustaQSG : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "Quadtube";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "Shells";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 8;
		Weapon.slotnumber 3;
		Weapon.SelectionOrder 300;
		Weapon.SlotPriority 60;
		Inventory.PickupSound "weapons/shellslide";
		Inventory.Pickupmessage "[3] - \c[brighterOrange]Quad-barreled shotgun\c- acquired.";
		Inventory.AltHUDIcon "QSG2A0";
		Tag "$PC_QUADSHOTGUNTAG";
		JustaWeapon.BarGraphic "ShellBar";
		JustaWeapon.CaseGraphic "Shell";
	}
	
	action void PC_FireQSG(bool half = false) {
		A_AlertMonsters();
		PC_PlayPowerModSounds();
		A_GunFlash();
		if(half) {
			A_startsound("Weapons/Quadaltfire",10,0,1);
			PC_FireBullets("PC_QSGProjectile", 9.0, 5.0, 18);
			PC_TakeAmmo("QuadTube", 2);
			PC_GunSmoke(-1,3,3);
			PC_GunSmoke(1,3,3);
		}
		else {
			A_startsound("weapons/Quadnormfire",10,1);
			PC_FireBullets("PC_QSGProjectile", 11.8, 7.3, 36);
			PC_TakeAmmo("QuadTube", 4);
			PC_GunSmoke(-1,3,4);
			PC_GunSmoke(1,3,4);
			PC_GunSmoke(-1,3,3);
			PC_GunSmoke(1,3,3);
		}
	}
	
	States
	{
		Spawn:
			QSG2 A -1;
			Stop;
		Ready:
			QSGI A 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Select:
			QSGM BA 1 A_WeaponReady(WRF_NOFIRE);
			QSGI A 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			QSGI A 1;
			QSGM AB 1;
			TNT1 A 0 A_lower;
			wait;
		Dryfire:
			QSGI A 4 A_startsound("Weapons/MGSGEmpty",11);
			Goto Ready;
		Fire:
			TNT1 A 0 A_JumpIfInventory("Quadtube",4,"FireBoth");
			TNT1 A 0 A_JumpIfInventory("Quadtube",2,"FireBottom");
			Goto dryfire;
		FireBoth:
			QSGI B 3 A_startsound("Weapons/QSGTriggerPull",11);
			QSGF A 1 Bright PC_FireQSG();
			QSGF B 1 Bright;
			QSGK B 1  {
				PC_QuakeCamera(3,6);
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_WeaponRecoil(9,7);
			}
		FinishFire:
			QSGK C 1;
			QSGK D 1 A_ZoomFactor(0.999);
			QSGK E 1;
			QSGK F 1 A_ZoomFactor(1.0);
			QSGK GHIJ 1;
			QSGK KLMN 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Goto Ready;
		Altfire:
			TNT1 A 0 A_JumpIfInventory("Quadtube",4,"FireTop");
			TNT1 A 0 A_JumpIfInventory("Quadtube",2,1);
			Goto dryfire;
		Firebottom:
			QSGI A 2 A_startsound("Weapons/QSGTriggerPull",11);
			QSGF C 1 bright PC_FireQSG(true);
			QSGF D 1 Bright;
			QSGK B 1 {
				PC_QuakeCamera(2,4);
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_WeaponRecoil(6,4);
			}
			Goto FinishFire;
		Firetop:
			TNT1 A 0 A_JumpIfInventory("Quadtube",2,1);
			Goto dryfire;
			QSGI A 2 A_startsound("Weapons/QSGTriggerPull",11);
			QSGF E 1 bright PC_FireQSG(true);
			QSGF F 1 Bright;
			QSGK B 1 {
				PC_QuakeCamera(2,4);
				A_ZoomFactor(0.99,ZOOM_INSTANT);
				PC_WeaponRecoil(6,4);
			}
			QSGK B 1;
			Goto FinishFire;
		Reload:
			TNT1 A 0 A_Jumpifinventory("Quadtube",4,"Ready");
			TNT1 A 0 A_Jumpifinventory("Quadtube",2,"Reloadtop");
			TNT1 A 0 A_Jumpifinventory("Shells",4,"Doublereload");
			QSGI A 1;
			Goto Reloadtop;
		Doublereload:
			QSGR ABCDE 1;
			QSGR F 3 A_startsound("Weapons/Quadopen",9,0,1);
			QSGR GHIJK 1;
			TNT1 AAAA 0 A_SpawnItemEx("Spentshell",Cos(Pitch)*25,-2,25-(Sin(Pitch)*25),Cos(Pitch)*FRandom(2,4),FRandom(-3,-6),-Sin(Pitch)*FRandom(3,6),0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH);
			QSGR K 10;
			QSGR LM 1;
			QSGR MNO 1;
			QSGR P 2
				{
				A_startsound("Weapons/Quadload",11,0,1);
				PC_AmmoIntoMag(2, true);
				}
			QSGR QR 1;
			QSGR S 8;
			QSGR TUV 1;
			QSR2 A 1;
			QSR2 B 2
				{
				A_startsound("Weapons/Quadload",11,0,1);
				PC_AmmoIntoMag(2, true);
				}
			QSR2 CD 1;
			QSR2 E 5;
			QSGR JIHF 1;
			TNT1 A 0 A_startsound("Weapons/Quadclose",12,CHANF_OVERLAP,1);
			QSGR EDCBA 2;
			QSGI A 1;
			Goto ready;
		Reloadtop:
			TNT1 A 0 A_Jumpifinventory("Shells",2,2);
			QSGI A 1;
			Goto Ready;
			QSGR ABCDE 1;
			QSGR F 3 A_startsound("Weapons/Quadopen",9);
			QSGR GHIJS 1;
			TNT1 AA 0 A_SpawnItemEx("Spentshell",Cos(Pitch)*25,-2,25-(Sin(Pitch)*25),Cos(Pitch)*FRandom(2,4),FRandom(-3,-6),-Sin(Pitch)*FRandom(3,6),0,SXF_NOCHECKPOSITION|SXF_TRANSFERPITCH);
			QSGR S 8;
			QSGR TUV 1;
			QSR2 A 1;
			QSR2 B 2
				{
				A_startsound("Weapons/Quadload",11,0,1);
				PC_AmmoIntoMag(2, true);
				}
			QSR2 CD 1;
			QSGR JIH 1;
			TNT1 A 0 A_startsound("Weapons/Quadclose",7);
			QSGR GFE 1;
			QSGR DCBA 2;
			QSGI A 1;
			Goto ready;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			QSGI A 1;
			QSGM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			QSGI A 1;
			QSGM AB 1;
			Goto Minethrow;
		Returnstate:
			QSGM BA 1;
			QSGI A 1;
			Goto Ready;
	}
}