class PC_Projectile : FastProjectile abstract
{
	enum ExplosionType
	{
		EType_Geometry,
		EType_Actor,
		EType_BleedingActor
	}
	
	override void BeginPlay()
	{
		super.BeginPlay();
		if(!speed) speed = trueSpeed * VEL_COEFF;
	}

    array<Actor> ignoreList;
    bool isBloodExplosionGenerator;
	
	const VEL_COEFF = 0.2787456; //ratio of bullet's real speed in ft/s to doom units

	mixin PC_LocationalDamage;

	virtual int Handle_MissileHit(Actor victim)
	{
		bool cantRip = (bRIPPER && (victim.bBOSS && bNOBOSSRIP || victim.bDONTRIP || victim.riplevelmin > ripperlevel || victim.riplevelmax > 0 && victim.riplevelmax < ripperlevel));
		
		if(target && (target.bDONTHARMSPECIES && victim.GetSpecies() == target.GetSpecies() || target.bDONTHARMCLASS && victim.GetClassName() == target.GetClassName()))
			return cantRip ? 0 : -1;
		
		int scaledDamage = truedamage;
		name dmgType = damageType;
		if(!bNOCRITICALS) [scaledDamage, dmgType] = GetLimbDamage(truedamage, damageType, pos, victim, target, self.bOMNIDIRECTIONAL, headSizeMul);
		if(dmgType == "Head" && headDamage) deathtype = headDamage;
		if(dmgType == "Arm" && armDamage) deathtype = armDamage;
		if(dmgType == "Dick" && dickDamage) deathtype = dickDamage;
		if(dmgType == "Leg" && legDamage) deathtype = legDamage;
		
		if(victim.bsolid || victim.bshootable)	//dont spawn puffs on casings,ammo,etc
		{
            if(!(victim.bNOBLOOD || victim.bINVULNERABLE || victim.bDORMANT || victim.bREFLECTIVE || (victim.bsolid && ! victim.bShootable)))
			victim.SpawnBlood( pos, angle, ceil(scaledDamage) );
		}
		
		victim.DamageMobj(self, target, ceil(scaledDamage), dmgType, 0, angle);
		
		// ( victim.bISMONSTER || victim.BloodType != 'Blood' ) 
		
		OnHitActor(target, dmgType);
		
		// [gng] prevent missile from ripping through or getting stuck on bosses
		return cantRip ? 0 : -1;
	}
	
	override int SpecialMissileHit(Actor victim)
	{
		if (victim == Target && !bHitOwner || (!victim.bSHOOTABLE && (target && target.player)))
		{
			return 1; //[inkoalawetrust] //This is default behavior though ?
		}
		
		if (bRIPPER)
		{
			if (ripAmount == 0)
			{
				return 0; // [Ace] We must use 0 here or else the projectile will keep ripping. Removing the ripper flag does not take effect until the next tic because of how ripping works.
			}
			if (LastActor != victim && Victim)
			{
				if(ripAmount > 0) ripAmount = ripAmount - 1;
				let retval = Handle_MissileHit(victim);
				LastActor = victim;
                return retval;
			}
			else
			{
				return 1;
			}
		}
        else
        {
            let retval = Handle_MissileHit(victim);
            LastActor = victim;
            return retval;
        }
		return -1;
	}
	
	virtual void ActivateLines()
	{
		if(noActivation == -1) return;
		if(noActivation == 1) noActivation=-1;
		
		let lt = LineActivatorTracer.DoTrace(self, angle, pitch, max(128, vel.length()));
		for(int i = 0; i < lt.HitLines.Size(); i++)
		{
			let ln = lt.HitLines[i];
			if(ln) ln.Activate(target, 0, SPAC_Impact);
		}
		if(BlockingLine) BlockingLine.Activate(target, 0, SPAC_Impact);
	}
	
	// [gng] optimized fastprojectile code
    // no excessive amount of steps, just a few linetracers
	virtual void FastProjectileTick()
	{
        vel.z -= GetGravity();
        double dist = bRANGED ? clamp(vel.Length(), 0, destroyRange) : vel.Length();
        INTERNAL_SpecLineTracer trac = INTERNAL_SpecLineTracer.Predict(self, vel.Unit(), dist, 0, 0x01000000, ignore: BlockingMobj);
        TraceResults specHit = trac.results;
        SetOrigin(specHit.HitPos, true);
		
        if(bRANGED)
        {
            destroyRange -= specHit.Distance;
            if(destroyRange <= 0)
            {
                Destroy();
                return;
            }
        }

        vector3 savedPos = pos;
        if(bRIPPER)
        {
            for(int i = 0; i < trac.hitActors.Size(); i++)
            {  
                BlockingMobj = trac.hitActors[i];
                if(!BlockingMobj) continue;
                SetOrigin((trac.hitActorsPosX[i], trac.hitActorsPosY[i], trac.hitActorsPosZ[i]), false);
                if(bBounceOnActors)
                {
                    if(!BounceActor(BlockingMobj, false))
                    {
                        ExplodeMissile(NULL, BlockingMobj);
                        OnExplode(FindExplosionType(BlockingMobj));
                    }
                    return;
                }

                if(BlockingMobj && ReflectOffActor(BlockingMobj)) 
                    return;

                let retval = SpecialMissileHit(BlockingMobj);

                if(retval == 0)
                {
                    ExplodeMissile(NULL, BlockingMobj);
                    OnExplode(FindExplosionType(BlockingMobj));
                    return;
                }
                else if(retval == 1)
                    continue;

                LastActor = BlockingMobj;
            }
            //SetOrigin(savedPos, false);
        }
        else if(specHit.HitType == TRACE_HitActor)
        {
            BlockingMobj = specHit.HitActor;
            if(BlockingMobj) 
            {
                SetOrigin((specHit.HitPos), false);
                if(bBounceOnActors)
                {
                    if(!BounceActor(BlockingMobj, false))
                    {
                        ExplodeMissile(NULL, BlockingMobj);
                        OnExplode(FindExplosionType(BlockingMobj));
                    }
                    return;
                }

                if(BlockingMobj && ReflectOffActor(BlockingMobj)) 
                    return;

                SpecialMissileHit(BlockingMobj);
                ExplodeMissile(NULL, BlockingMobj);
                OnExplode(FindExplosionType(BlockingMobj));
                return; 
            }     
        }

        if(specHit.HitTexture == skyflatnum)
        {
            Destroy();
            return;
        }

        double dontcare;
        F3DFloor stilldontcare;
        switch(specHit.HitType)
        {
            case TRACE_HitWall:
                BlockingLine = specHit.HitLine;
                if(BounceWall())
                {
                    PlayBounceSound(false);
                    return;
                }

                SetOrigin(specHit.HitPos, false);

                ExplodeMissile(BlockingLine, NULL);
                OnExplode(EType_Geometry);
                return;

                break;
            case TRACE_HitFloor:
                SetOrigin(specHit.HitPos, false);
                BlockingFloor = specHit.HitSector;
                ExplodeMissile(NULL, NULL);
                OnExplode(EType_Geometry);
                return;

                break;

            case TRACE_HitCeiling:
                SetOrigin(specHit.HitPos, false);
                BlockingCeiling = specHit.HitSector;
                ExplodeMissile(NULL, NULL);
                OnExplode(EType_Geometry);
                return;

                break;
        }

        if (!CheckNoDelay())
			return;

		// Advance the state
		if (tics != -1)
		{
			if (tics > 0) tics--;
			while (!tics)
			{
				if (!SetState (CurState.NextState))
				{ // mobj was removed
					return;
				}
			}
		}
	}
	
	override void Tick()
	{
		if (!bNOTIMEFREEZE && IsFrozen())
			return;
		
		activateLines();
		
		FastProjectileTick(); //We just use our own copy of the Tick() method for bouncing.
	}
	
	// [Ace] Override these if you want to do stuff when something happens.
	protected virtual void OnHitActor(Actor target, Name dmgType) {}
	protected virtual void OnExplode(int type) {}
	
	ExplosionType FindExplosionType (Actor Victim) //Determine what impact type to use.
	{
		If (!Victim) //No impact victim ? Probably level geometry.
			return EType_Geometry;
		
		If (((Victim.bShootable && Victim.bCorpse) || Victim.bKilled ) && Victim.bNoBlood) //https://www.youtube.com/watch?v=K63AVSCPcSI
			return EType_Actor;
		
		return EType_BleedingActor; //https://www.youtube.com/watch?v=BlrjHLnNzAo
	}
	
	// [Ace] In case you have attached anything to this item, calling OwnerDied allows you to do some effects on death.
	protected void CallOwnerDied()
	{
		for (Inventory next = Inv; next != null; next = next.Inv)
		{
			next.OwnerDied();
		}
	}

	double ExtraDamageFactor;
	protected Actor LastActor;
	
	Array<Actor> act_hits;
	Actor hitactor;
	Actor LastRipped, PreLastRipped; //The actor that a ripper last hit. Used for the RIPONCE flag.
	int ripamount;
	Property RipperCount : ripamount;
	
	int destroyRange;
	Property ProjectileRange : destroyRange;
	
	double truedamage;
	Property BaseDamage : truedamage;
	
	double trueSpeed;
	Property SpeedFPS : trueSpeed;
	
    double headSizeMul;
	Property HeadSizeMultiplier : headSizeMul;
	
	private int BehaviorFlags;
	flagdef NoCriticals: BehaviorFlags, 0;
	flagdef Omnidirectional: BehaviorFlags, 1;
	flagdef RipOnce: BehaviorFlags, 2;
	flagdef RANGED: BehaviorFlags, 3;
	
	name headDamage, armDamage, dickDamage, legDamage;
	property LimbDeathTypes : headDamage, armDamage, dickDamage, legDamage;
	
	int noActivation;

	Default
	{
		// [Ace] Speedy projectiles with a large radius are more performant, but they don't work so well with switches that rely on hitscan activation
		// if the linedefs are packed right in front of a wall. Normally this shouldn't be a problem, but in some cases it is, such as Sigil's E5M1 switch at map start.
		Speed 0;
		Mass 25;
		Radius 1;
		Height 2;
		Projectile;
		+GETOWNER
		+NODAMAGETHRUST
		+NOEXTREMEDEATH
		+FORCERADIUSDMG
		+HITTRACER
		+NOBOSSRIP
		+RIPPER
		-NOGRAVITY
		+PC_Projectile.RipOnce;
		+NOTIMEFREEZE;
		ProjectileKickBack 20;
		Renderstyle "Add";
		// Decal "ConcreteBullethole";
		Scale 0.15;
		PC_Projectile.RipperCount 1;
		PC_Projectile.BaseDamage 5;
		PC_Projectile.SpeedFPS 10; //[nV] this is the muzzle velocity of the projectile measured in feet-per-second. if your projectile isn't based on something real, setting the speed property works as normal and overrides this.
        PC_Projectile.HeadSizeMultiplier 1;
		Gravity 0.1;
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			TRAC A -1 BRIGHT;
			Stop;
		Death: // [Ace] Wall.
			TNT1 A 0
			{
				CallOwnerDied();
				OnExplode(EType_Geometry);

				//A_StopAllSounds();
			}
			Stop;
		Crash: // [Ace] Dormant/NoBlood enemies.
			TNT1 A 0
			{
				CallOwnerDied();
				OnExplode(EType_Actor);
				//console.printf("hit");
			}
			Stop;
		XDeath: // [Ace] Bleeding enemies.
			TNT1 A 0
			{
				CallOwnerDied();
				OnExplode(EType_BleedingActor);
			}
			Stop;
	}
}

class LineActivatorTracer : LineTracer
{
	Actor src;
	Array<Line> HitLines;

	play static LineActivatorTracer DoTrace(Actor src, double tangle, double tpitch, double dist, uint traceflags = 0)
	{
		LineActivatorTracer tracer = new("LineActivatorTracer");
		if(tracer) 
		{
			tracer.src = src;
			vector3 dir = PC_Math.VecFromAngles(tangle, tpitch);
			tracer.Trace(src.pos, src.CurSector, dir, dist, traceflags);
		}
		return tracer;
	}

	// Thanks to PhantomBeta 
	// (https://github.com/Doom2fan/Se7evidas/blob/master/PK3%20Source/S7ZScript/Bases/S7_Projectile/Linetracer.ZS)
	transient Array<F3DFloor> ffloorsToIgnore;
	ETraceStatus HandleWall() 
	{
		let hl = Results.HitLine;
		HitLines.push(hl);

		if (Results.Tier == TIER_Upper || Results.Tier == TIER_Lower)
			return TRACE_Stop;

		if (Results.ffloor && ffloorsToIgnore.Find (Results.ffloor) == ffloorsToIgnore.Size ())
		{
			ffloorsToIgnore.Push (Results.ffloor);
			return TRACE_Stop;
		}

		if (Results.Tier == TIER_Middle && !hl.backsector)
			return TRACE_Stop;

		if (Results.Tier == TIER_Middle && (hl.flags & Line.ML_Blocking) && (hl.flags & Line.ML_TwoSided))
			return TRACE_Skip;

		if ((hl.flags & Line.ML_3DMidTex) && !(hl.flags & Line.ML_3DMidTex_Impass))
			return TRACE_Stop;

		if (hl.flags & (Line.ML_Blocking | Line.ML_BlockEverything))
			return TRACE_Stop;

		return TRACE_Skip;
	}

	override ETraceStatus TraceCallback()
	{
		if(results.HitType == Trace_HitWall)
		{
			let stat = HandleWall();
			return stat;
		}
		if(results.HitType == Trace_HitActor)
		{
			return Trace_Skip;
		}
		return Trace_Stop;
	}
}

class INTERNAL_SpecLineTracer : LineTracer
{
    actor target, src;
    Array<actor> hitActors;
    Array<double> hitActorsPosX;
    Array<double> hitActorsPosY;
    Array<double> hitActorsPosZ;
    
    play static INTERNAL_SpecLineTracer Predict(Actor src, vector3 direction, double maxDist, ETraceFlags traceFlags, uint wallMask = 0xFFFFFFFF, bool ignoreAllActors = false, Actor ignore = null)
	{
		INTERNAL_SpecLineTracer tracer = new("INTERNAL_SpecLineTracer");
		if(tracer) 
		{
			tracer.target = src.target;
            tracer.src = src;
			tracer.Trace(src.pos, src.CurSector, direction, maxDist, traceFlags, wallMask, ignoreAllActors, ignore);
		}
		return tracer;
	}
    
    override ETraceStatus TraceCallback()
    {
        if(Results.HitType == TRACE_HitActor)
        {
            if(!Results.HitActor) return TRACE_Skip;
            
            if(target && src && Results.HitActor == target && !src.bHitOwner)
                return TRACE_Skip;
            else if(Results.HitActor.bSHOOTABLE) 
            {
                if(src.bRIPPER)
                {
                    hitActors.Push(Results.HitActor);
                    hitActorsPosX.Push(Results.HitPos.X);
                    hitActorsPosY.Push(Results.HitPos.Y);
                    hitActorsPosZ.Push(Results.HitPos.Z);
                    return TRACE_Continue;
                }
                return TRACE_Stop;
            }
            else 
                return TRACE_Skip;
        }

        return TRACE_Continue;
    }
}
