class PC_ShotgunProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 10;
		PC_Projectile.RipperCount 1;
		PC_Projectile.SpeedFPS 1145;
		Obituary "%o Had their skull splattered by a hail of shot.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("shotgunpuff", (Vec3Offset(0,0,0)));
	}
}

class PC_SSGProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 16;
		PC_Projectile.RipperCount 1;
		PC_Projectile.SpeedFPS 1100;
		Obituary "%o realized that double-barrel shotguns tend to fuck things up.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("SSGpuff", (Vec3Offset(0,0,0)));
	}
}

class PC_ShotvolverProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 200;
		PC_Projectile.SpeedFPS 1600;
		-RIPPER
		Obituary "%o was smeared across. . . well, everything, by a literal handcannon.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("ESSGPuff", (Vec3Offset(0,0,0)));
	}
}
