class PC_BattleRifleProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 45;
		PC_Projectile.RipperCount 2;
		PC_Projectile.SpeedFPS 2837;
		Decal "Rocketscorch";
		Obituary "%o was crossmapped.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("EHMGpuff", (Vec3Offset(0,0,0)));
	}
	override void OnHitActor(Actor target, Name dmgType)
	{
		Spawn("EHMGpuff", (Vec3Offset(0,0,0)));
	}
}

class PC_HMGProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 20;
		PC_Projectile.RipperCount 1;
		PC_Projectile.SpeedFPS 2837;
		Decal "Rocketscorch";
		Obituary "%o found out that the Rotary canon their enemy carried was explosive.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("EHMGpuff", (Vec3Offset(0,0,0)));
	}
	override void OnHitActor(Actor target, Name dmgType)
	{
		Spawn("EHMGpuff", (Vec3Offset(0,0,0)));
	}
}

class PC_HMGAltProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 400;
		PC_Projectile.RipperCount -1;
		PC_Projectile.SpeedFPS 2837;
		Decal "Rocketscorch";
		Obituary "%o found out that the Rotary canon their enemy carried was explosive.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("EHMGAltpuff", (Vec3Offset(0,0,0)));
	}
	override void OnHitActor(Actor target, Name dmgType)
	{
		Spawn("EHMGAltpuff", (Vec3Offset(0,0,0)));
	}
}

class PC_AssaultRifleProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 25;
		PC_Projectile.RipperCount 2;
		PC_Projectile.SpeedFPS 3260;
		Obituary "%o was crossmapped.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("apuff", (Vec3Offset(0,0,0)));
	}
}

class PC_MinigunProjectile : PC_Projectile
{
	Default
	{
		PC_Projectile.BaseDamage 20;
		PC_Projectile.SpeedFPS 3260;
		-RIPPER
		Obituary "%o Was penetrated more times than they could count due to their killer having a FRICKIN' MINIGUN.";
	}
	
	override void OnExplode(int type)
	{
		Spawn("apuff", (Vec3Offset(0,0,0)));
	}
}