class JustsomeC4 : Justaweapon
{
	Default
	{
		Weapon.AmmoType1 "C4ammo";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.slotnumber 1;
		Weapon.SlotPriority 20;
		Obituary "%k Was SHOT THROUGH THE HEART.";
		Weapon.SelectionOrder 3000;
		Weapon.UpSound "Weapon/Select";
		Inventory.PickupSound "Pistol/cock";
		Inventory.Pickupmessage "[0] - \c[Darkgray]C4 Eplosive\c- acquired.";
		Tag "$PC_C4TAG";
		Inventory.AltHUDIcon "PIPBB0";
		Scale 1;
	}
	
	int throwStrength;
	
	action bool PC_GetActiveC4() {
		let plr = PCmarine(self);
		if(plr.ActiveC4.Size())
			return true;
		return false;
	}
	
	action void PC_ThrowC4(int force) {
		let plr = PCmarine(self);
		let c4 = A_FireProjectile("ThrownPipebombs");
		c4.vel *= force;
		plr.ActiveC4.Push(c4);
		A_StartSound("Weapons/grenadethrow", 10);
		A_TakeInventory("C4ammo", 1, TIF_NOTAKEINFINITE);
		invoker.throwStrength = 0;
	}
	
	action void PC_DetC4() {
		let plr = PCmarine(self);
		for(int i = 0; i < plr.ActiveC4.Size(); i++) {
			let c4 = ThrownPipebombs(plr.ActiveC4[i]);
			if(c4) c4.SetState(c4.FindState("Detonate"));
		}
		plr.ActiveC4.Clear();
	}
	
	States
	{
	Spawn:
		PIPB A -1;
		Stop;
	Select:
		TNT1 A 1 A_JumpIfInventory("C4ammo",1,"Ammoselect");
		Goto NoAmmo;
	Ammoselect:
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detselect");
		DKPM BA 1 A_WeaponReady(WRF_NOFIRE);
		DKPB A 1 A_WeaponReady(WRF_NOFIRE);
		Goto ready;
	Detselect:
		DETO ABCD 1 A_weaponready;
		Goto ready;
	Deselect:
		TNT1 A 0 A_JumpIfInventory("C4ammo",1,1);
		Goto emptyselect;
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detunselect");
		DKPB A 1;
		DKPM AB 1;
		TNT1 A 0 A_lower;
		wait;
	Emptyselect:
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detunselect");
		TNT1 A 0 A_lower;
		Wait;
	Detunselect:
		DETO DCBA 1;
		TNT1 A 0 A_lower;
		wait;
	Haveammonow:
		DKPB EDCB 1 A_WeaponReady(WRF_NOFIRE | WRF_NOSWITCH);
		Goto ready;
	Ready:
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detready");
		DKPB A 1 A_WeaponReady(wrf_allowzoom|wrf_allowuser1|wrf_allowuser2);
		Loop;
	Detready:
		DETO D 1 A_WeaponReady(wrf_allowzoom|wrf_allowuser1|wrf_allowuser2);
		Loop;
	Noammo:
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detready");
		TNT1 A 0 A_JumpIfInventory("C4ammo",1,"Haveammonow");
		TNT1 A 1 A_WeaponReady(wrf_nofire | wrf_allowzoom|wrf_allowuser1|wrf_allowuser2);
		loop;
	fire2:
		TNT1 A 0 A_JumpIfInventory("c4ammo",1,1);
		Goto detready;
		DETO DCBA 1;
		Goto Hold;
	Altfire:
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),1);
		Goto ready;
		DETO EF 1;
		DETO G 2 {
			PC_PlayPowerModSounds();
			A_startsound("Weapons/pipebutton",10);
			PC_DetC4();
			A_alertmonsters(6200);
		}	
		DETO G 2;
		DETO FEDCBA 1;
		TNT1 A 0 A_JumpIfInventory("C4ammo",1,1);
		Goto Noammo;
		DKPB EDCB 1;
		Goto Ready;
	Fire:
		TNT1 A 0 A_jumpif(PC_GetActiveC4(),"Fire2");
		TNT1 A 0 A_JumpIfInventory("C4ammo",1,1);
		Goto Noammo;
		DKPB BCDE 1;
	Hold:
		TNT1 A 1 {
			int maxStrength = 35;
			if(FindInventory("PowerStrength")) maxStrength = 55;
			if(!invoker.throwStrength) invoker.throwStrength = 15;
			else if(invoker.throwStrength < maxStrength) invoker.throwStrength++;
		}
		TNT1 A 0 A_ReFire();
		DKPB FGHI 1;
		TNT1 A 0 PC_ThrowC4(invoker.throwStrength);
		DKPB JKKLMNO 1;
		DETO ABC 1;
		Goto Detready;
	User1:
		TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
		Goto Ready;
		TNT1 A 0 A_JumpIfInventory("C4ammo",1,1);
		Goto Emptythrow1;
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detthrow1");
		DKPM AB 1;
		Goto nadethrow;
	Emptythrow1:
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detthrow1");
		TNT1 A 2;
		Goto Nadethrow;
	Detthrow1:
		DETO CA 1;
		Goto Nadethrow;
	User2:
		TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
		Goto Ready;
		TNT1 A 0 A_JumpIfInventory("C4ammo",1,1);
		Goto Emptythrow2;
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detthrow2");
		DKPM AB 1;
		Goto Minethrow;
	Emptythrow2:	
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detthrow2");
		TNT1 A 2;
		Goto Minethrow;
	Detthrow2:
		DETO CA 1;
		Goto Minethrow;
	Returnstate:
		TNT1 A 0 A_JumpIfInventory("C4ammo",1,1);
		Goto Noammoreturn;
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detreturn");
		DKPM BA 1;
		DKPB A 1;
		Goto Ready;
	Noammoreturn:
		TNT1 A 0 A_JumpIf(PC_GetActiveC4(),"Detreturn");
		TNT1 A 3;
		Goto noammo;
	Detreturn:
		DETO ACD 1;
		Goto Detready;
	}
}

class ThrownPipebombs : Actor
{
	Default
	{
		Projectile;
		Radius 6;
		Height 6;
		Speed 1;
		Damage 0;
		scale 0.5;
		Gravity 0.8;
		DamageType "PipeExplosion";
		Alpha 256;
		Obituary "%o tripped over the pipebomb.";
		+MISSILE;
		+WINDTHRUST;
		-NOGRAVITY;
		-NOTELEPORT;
		-BOUNCEONACTORS;
		+DROPOFF;
		+DontHarmSpecies;
		+Thruspecies;
		+Mthruspecies;
		+CANBOUNCEWATER;
		+GHOST;
		-NOGRAVITY;
		+ROLLSPRITE;
		+ROLLCENTER;
		+STRETCHPIXELS;
		+movewithsector;
		BounceSound "Weapon/Pipebounce";
		DeathSound "Weapon/Pipebounce";
		Species "ThrownPipebombs";
		WallBounceFactor .5;
		bouncecount 3;
		BounceType "Doom";
		BounceFactor 0.45;
		Mass 2;
	}
	
	bool detonated;
	
	override void Touch(Actor toucher) {
		let heldAmmo = toucher.FindInventory("C4Ammo");
		if(heldAmmo && toucher.CountInv("C4Ammo") >= heldAmmo.maxAmount) return;
		let c4 = Spawn("C4Ammo", pos);
		if(!c4) return;
		c4.Touch(toucher);
		Destroy();
	}
	
	States
	{
	Spawn:
		PIPB BBBBBBBBBB 2 A_SetRoll(roll+20, SPF_INTERPOLATE);
		TNT1 A 0 A_Startsound("Weapons/C4beep", 50);
		PIPB CCCCC 2 Bright Light("MineLight1") A_SetRoll(roll+20, SPF_INTERPOLATE);
		Loop;
	Death:
		TNT1 A 0 {
			bSPECIAL = true;
			bMISSILE = false;
			A_ChangeLinkFlags(false);
			A_SetRoll(0);
			if(detonated) return findstate("Detonate");
			return findstate(null);
		}
		Goto Lying;
	Lying:
		PIPB B 20;
		PIPB C 10 Bright Light("MineLight1") A_Startsound("Weapons/C4beep", 50);
		Loop;
	Detonate:
		PIPB D 4 Bright Light("MineLight1") {
			detonated = true;
			bSPECIAL = false;
		}
		TNT1 A 0 {
			bMISSILE = false;
			bNOINTERACTION = true;
			A_Stop();
		}
		TNT1 A 0 A_startsound("rocket/boom",99,0,1);
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 AAAAAA 0 A_spawnitemex("smallkaboom",0,random(35,-35),random(35,-35));
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0
		{
			A_explode(300,100,1,1,0,0,0,"Apuff","C4");
			A_explode(200,200,1,1,0,0,0,"Apuff","C4");
			A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		}
		TNT1 A 0
		{
			Radius_quake(7,8,0,10,0);
			Radius_Quake(4,8,0,28,0);
			Radius_Quake(2,8,0,50,0);
		}
		TNT1 AAAA 0 
		{
			A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
		}
		TNT1 AAAAA 5 A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
		TNT1 A 0 A_die("Goaway");
		Stop;
	LessExplode:
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 
		{
			A_explode(300,100,1,1,0,0,0,"Apuff","C4");
			A_explode(200,200,1,1,0,0,0,"Apuff","C4");
			A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		}
		TNT1 A 0
		{
			Radius_quake(7,8,0,10,0);
			Radius_Quake(4,8,0,28,0);
			Radius_Quake(2,8,0,50,0);
		}
		TNT1 A 0 A_die("Goaway");
		Stop;
		}
}

class C4Kaboom : Actor
{
	Default
	{
		Radius 0;
		Height 0;
		Speed 0;
		Scale 0.5;
		Damagetype "C4";
		-NOGRAVITY;
		-NOTELEPORT;
		+DROPOFF;
		+DontHarmSpecies;
		+Thruspecies;
		+CANBOUNCEWATER;
		-NOGRAVITY;
		+movewithsector;
		BounceType "Doom";
		Damagetype "Rocket/boom";
		Obituary "%o tripped over the pipebomb.";
	}
	States
	{
	Spawn:
		TNT1 A 0	Nodelay A_startsound("rocket/boom",99,0,1);
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128); 
		TNT1 AAAAAA 0 A_spawnitemex("smallkaboom",0,random(35,-35),random(35,-35));
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 A_explode(300,100,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(200,200,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 Radius_quake(7,8,0,10,0);
		TNT1 A 0 Radius_Quake(4,8,0,28,0);
		TNT1 A 0 Radius_Quake(2,8,0,50,0);
		TNT1 AAAA 0
		{
			A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
		}
		TNT1 AAAAA 5 A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
		Stop;
	LessExplode:
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 A_explode(300,100,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(200,200,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 Radius_quake(3,8,0,10,0);
		TNT1 A 0 Radius_Quake(1,8,0,28,0);
		Stop;
	}
}
