class BattleRiflemag : Ammo
{
	Default
	{
	  Inventory.Amount 0;
	  Inventory.MaxAmount 12;
	  Ammo.BackpackAmount 0;
	  Ammo.BackpackMaxAmount 12;
	  Inventory.Icon "RMAGA0";
	  +INVENTORY.IGNORESKILL;
	}
}
//ACTOR Weaponzoom : Inventory { Inventory.MaxAmount 1 }
class BattleRiflecock : Weaponzoom {}

class Justabuttrifle : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "BattleRiflemag";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "PC_ExplosiveBullets";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 12;
		Weapon.slotnumber 4;
		Weapon.SelectionOrder 700;
		Weapon.SlotPriority 20;
		Obituary "%k was crossmapped.";
		Inventory.AltHUDIcon "MGLXA0";
		Inventory.PickupSound "Weapon/Riflecock";
		Inventory.Pickupmessage "[4] - \c[Explosiveyellow]Battle rifle\c- acquired.";
		Tag "$PC_BATTLERIFLETAG";
		-Weapon.noautofire;
		JustaWeapon.BarGraphic "XBullBar";
		JustaWeapon.CaseGraphic "XBullet";
	}
	
	action void PC_FireBattleRifle(double spreadMod = 1.0)
	{
		PC_PlayPowerModSounds();
		A_startsound("Weapons/BRFireAlt",6,CHANF_OVERLAP);
		A_startsound("Weapons/BRFire",5,CHANF_OVERLAP);
		A_AlertMonsters();
		
		PC_QuakeCamera(2,3);
		A_GunFlash();
		PC_GunSmoke(0,3,3);
		PC_GunSmoke(-5,3,3);
		PC_GunSmoke(5,3,3);
		
		if(CountInv("WeaponZoom") == 0) { PC_SetFrame(random(0, 2)); }
		
		PC_FireBullets("PC_BattleRifleProjectile", 0.1 * spreadMod, 0.1 * spreadMod);
		PC_TakeAmmo("BattleRifleMag");
	}
	
	States
	{
		Spawn:
			MGLX A -1;
			Stop;
		Select:
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Unzoom");
			HEUP BA 1 A_WeaponReady(WRF_NOFIRE);
			HE1G A 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect:
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Zoomdeselect");
			HE1G A 1;
			HEUP AB 1;
			TNT1 A 0 A_lower;
			wait;
		Zoomdeselect:
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_Takeinventory("RLInfrared",1);
			TNT1 A 0 A_ZoomFactor(1.0,ZOOM_INSTANT);
			TNT1 A 0 A_SetCrosshair(0);
			HEUG HGFEDCBA 1;
			HE1G A 1;
			HEUP AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Readyzoom");
			HE1G A 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Readyzoom:
			TNT1 A 0 A_GiveInventory("Weaponzoom",1);
		Readyzoom2:
			SNIP B 2 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2|WRF_NOBOB);
			Loop;
		Zoomedtemp:
			SNIP B 6 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2|WRF_NOSECONDARY);
			Goto Readyzoom;
		Unzoomedtemp:
			HE1G A 6 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2|WRF_NOSECONDARY);
			Goto Ready;
		Dryfire:
			HE1G A 16 A_startsound("Weapons/Rifleempty",11,0);
			HE1G A 4 a_Clearrefire;
			Goto ready;
		DryUnzoom:
			TNT1 A 0 A_Takeinventory("RLInfrared",1);
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0,ZOOM_INSTANT);
			TNT1 A 0 A_SetCrosshair(0);
			HEUG HGFEDCBA 1;
			goto Dryfire;
		Fire:
			TNT1 A 0 A_JumpIfInventory("Weaponzoom",1,"FireZoom");
			TNT1 A 0 A_JumpIfInventory("BattleRiflemag",1,1);
			Goto Dryfire;
			HE1F A 1 Bright PC_FireBattleRifle();
			HE2F A 1 Bright {
				A_ZoomFactor(0.97,ZOOM_INSTANT);
				PC_SetFrame(random(0, 2));
				PC_SpawnCasing("ARCasing", 24, 4, 32, frandom(2.0, 3.0), frandom(5.0, 6.0), frandom(4.0, 5.0));
				PC_WeaponRecoil(0.65,0.35);
			}
			HE3F A 1 A_ZoomFactor(0.99);
			HE3F B 2;
			HE3F C 1 A_ZoomFactor(1.0);
			HE3F D 1;
			HE1G A 2;
			TNT1 A 0 A_ReFire("Fire");
			Goto ready;
		FIreZoom:
			TNT1 A 0 A_giveinventory("Weaponzoom",1);
			TNT1 A 0 A_JumpIfInventory("BattleRiflemag",1,1);
			Goto DryUnzoom;
			SNIP B 1 Bright PC_FireBattleRifle(0.25);
			SNIP B 1 {
				A_ZoomFactor(2.4,ZOOM_INSTANT);
				PC_WeaponRecoil(0.35,0.15);
			}
			SNIP B 2 A_ZoomFactor(2.5);
			SNIP A 5;
			TNT1 A 0 A_ReFire("FireZoom");
			Goto Readyzoom;
		Flash:
			TNT1 A 2 A_Light2;
			TNT1 A 2 A_Light1;
			Goto LightDone;
		Reload:
			TNT1 A 0 A_Jumpifinventory("Weaponzoom",1,"Unzoom4Reload");
			TNT1 A 0 A_JumpIfInventory("BattleRiflemag", 12, 2);
			TNT1 A 0 A_JumpIfInventory("PC_ExplosiveBullets", 1, "ReloadWork");
			HE1G A 1;
			Goto ready;
		Unzoom4Reload:
			TNT1 A 0 A_JumpIfInventory("BattleRiflemag", 12, "ReadyZoom");
			TNT1 A 0 A_Takeinventory("RLInfrared",1);
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_ZoomFactor(1.0,ZOOM_INSTANT);
			TNT1 A 0 A_SetCrosshair(0);
			HEUG HGFEDCBA 1;
			Goto Reload;
		Reloadwork:
			TNT1 A 0 A_JumpIfInventory("BattleRiflemag",1,"ReloadWork2");
			TNT1 A 0 A_GiveInventory("BattleRiflecock",1);
		ReloadWork2:
			HRE1 A 1 A_startsound("Weapon/BRRaise",9,0);
			HRE1 BCDEFGHIJKLMNO 1;
			TNT1 A 0 A_startsound("Weapon/BRMagRelease",9,0);
			HRE1 P 4;
			HRE1 QRSTUVW 1;
			HRE1 X 6;
			HRE1 YZ 1;
			HRE2 A 1;
			TNT1 A 0 A_startsound("Weapon/BRMagPunch",11,0);
			HRE2 B 2;
			TNT1 A 0 A_startsound("Weapon/BRMagPunch2",10,0);
			HRE2 C 2;
			TNT1 A 0 A_startsound("Weapon/BRMagEject",9,0);
			HRE2 DEFGHI 1;
			TNT1 A 0 A_FireProjectile("ARclipspawner",0,0,0,1);
			HRE2 J 1;
			HRE2 K 12;
			HRE2 LMNOPQR 1;
			TNT1 A 0 A_startsound("Weapon/BRMagInsert",9,0);
			HRE2 STU 1;
			TNT1 A 0 PC_AmmoIntoMag();
			HRE2 VVWWWW 1;
			HRE2 XYZ 1;
			HRE3 AB 1;
			TNT1 A 0 A_JumpIfInventory("BattleRiflecock",1,"Reloadcockfinish");
			TNT1 A 0 A_startsound("Weapon/BRLower",9,0);
			HRE1 LKJIHGFEDCBA 1;
			Goto Ready;
		Reloadcockfinish:
			HRE3 CEFGG 1;
			TNT1 A 0 A_startsound("Weapon/BRBoltBack",11,0);
			HRE3 HIJ 1;
			HRE3 K 16;
			TNT1 A 0 A_startsound("Weapon/BRBoltForward",9,0);
			HRE3 LM 2;
			TNT1 A 0 A_startsound("Weapon/BRBoltClose",11,0);
			HRE3 NO 2;
			TNT1 A 0 A_startsound("Weapon/BRLower",9,0);
			HRE1 LKJIHGFEDCBA 1;
			HE1G A 2 A_TakeInventory("BattleRiflecock",1);
			Goto Ready;
		AltfireReturn:
			R1FG A 1 Offset(90,79);
			R1FG A 1 Offset(75,69);
			R1FG A 1 Offset(60,60);
			R1FG A 1 Offset(45,52);
			R1FG A 1 Offset(30,45);
			R1FG A 1 Offset(15,39);
			R1FG A 1 Offset(1,35);
			Goto Ready;
		Altfire:
			TNT1 A 0 A_JumpIfInventory("Weaponzoom",1,"UnZoom");
			TNT1 A 0 A_GiveInventory("Weaponzoom",1);
			TNT1 A 0 A_StartSound("PCAssaultRifle/ADSIn",11);
			HEUG ABCD 1;
			TNT1 A 0 A_ZoomFactor(1.25);
			HEUG EFGH 1;
			TNT1 A 0 A_startsound("Weapons/ScopeZI",120,0);
			TNT1 A 0 A_Giveinventory("RLInfrared",1);
			TNT1 A 0 A_ZoomFactor(2.5,ZOOM_INSTANT);
			TNT1 A 0 A_SetCrosshair(8);
			Goto Zoomedtemp;
		UnZoom:
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_Takeinventory("RLInfrared",1);
			TNT1 A 0 A_StartSound("PCAssaultRifle/ADSOut",11);
			TNT1 A 0 A_ZoomFactor(1.25, ZOOM_INSTANT);
			TNT1 A 0 A_ZoomFactor(1.0);
			TNT1 A 0 A_SetCrosshair(0);
			HEUG HGFEDCBA 1;
			Goto UnZoomedtemp;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			HE1G A 1 A_Jumpifinventory("Weaponzoom",1,"Unzoom4Nade");
			HE1G A 1;
			HEUP AB 1;
			Goto nadethrow;
		Unzoom4Nade:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_Takeinventory("RLInfrared",1);
			TNT1 A 0 A_ZoomFactor(1.0,ZOOM_INSTANT);
			TNT1 A 0 A_SetCrosshair(0);
			HEUG HGFEDCBA 1;
			HE1G A 1;
			HEUP AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			HE1G A 1 A_Jumpifinventory("Weaponzoom",1,"Unzoom4Mine");
			HE1G A 1;
			HEUP AB 1;
			Goto Minethrow;
		Unzoom4Mine:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			TNT1 A 0 A_TakeInventory("Weaponzoom",1);
			TNT1 A 0 A_Takeinventory("RLInfrared",1);
			TNT1 A 0 A_ZoomFactor(1.0,ZOOM_INSTANT);
			TNT1 A 0 A_SetCrosshair(0);
			HEUG HGFEDCBA 1;
			HE1G A 1;
			HEUP AB 1;
			Goto Minethrow;
		Returnstate:
			HEUP BA 1;
			HE1G A 1;
			Goto Ready;
	}
}