class PCDTechRifleMarine : Follower_Marine
{	
	Default
	{
		Tag "Minigun Marine";
		
		Translation "112:127=176:191";
		
		DeathSound "Marine/EnergyDeath";
		Painsound "Marine/EnergyPain";
		Seesound "Marine/EnergySee";
		
		DamageFactor "FriendMarineDamage", 0;
	}
	
	Override Void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		PrimAmmo = 60;
		SecAmmo = 15;
		
		A_StartSound("Marine/EnergySee",CHAN_VOICE);
	}
	
	override void Tick() 
	{
		super.Tick();
		
		if (isFrozen())
		{
			return;
		}
		/*
		if(!master)
		{
			Spawn("TeleportFog", (pos.x, pos.y, pos.z + height * 0.5));
			Destroy();
			return;
		}*/
		
		if(health < default.health && HealTimer <= 0)
		{
			if(random(1,20) == 3) { A_Pain(); }
			switch(random(1,3))
			{
				default:
				case 1:
					A_StartSound("Pickup/flaskuse",0);
					A_SetHealth(health + 5);
					break;
				case 2:
					A_StartSound("Pickups/Pstimuse",0);
					A_SetHealth(health + 15);
					break;
				case 3:
					A_StartSound("Pickup/pmeduse",0);
					A_SetHealth(health + 25);
					break;
			}
			HealTimer = random(70,140);
		}
		
		if (health <= 5 && !Gibbed && !InStateSequence(curstate, FindState("FakeDeath")))
		{
			A_SetHealth(default.health);
			SetStateLabel("FakeDeath");
		}
		
		if(health <= default.health / 2 && target != master) { bFRIGHTENED = true; }
		else { bFRIGHTENED = false; }
		
		HealTimer--;
	}
	
	Override bool CanCollideWith(Actor other, bool Passive)
	{
		If(!Other) 
		Return False;
		If(Other && !Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}			
			Return True;
		}
		If(Other && Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}
			Return True;
		}
		Return True;
	}
	
	override bool Used(Actor user)
	{
		let plr = PCMarine(user);
		
		master = user;
		
		if(InStateSequence(curstate, FindState("FakeDeath")))
		{
			//[Pop] Maybe spawn particles or something
			SetStateLabel("FakeRaise");
		}
		else
		{
			SetIdle = !SetIdle;
			if(SetIdle) { A_StartSound("Marine/EnergySee",CHAN_VOICE); }
			else { A_StartSound("Marine/EnergySee",CHAN_VOICE); }
			//[Pop] Invert This basically
		}
		
		return Super.Used(user);
	}
	
	action void DTechRifleMarine_Fire(bool which)
	{	
		if(which)
		{
			A_StartSound("zombie/PistolFire", 0, CHANF_OVERLAP, 0.85);
			A_CustomMissile("Marinetracer",28,9,frandom(-2,2),CMF_OFFSETPITCH,frandom(-1,1));
			A_SpawnItemEx("PistolCasing", 12, 6, 30, Random(2, 6), 0, Random(1, 3), Random(-80, -90), 128);
			A_AlertMonsters(0,AMF_TARGETEMITTER);
			invoker.SecAmmo--;
		}
		else
		{
			A_StartSound("Weapons/DTRFire", 0, CHANF_OVERLAP, 1, ATTN_NORM);
			A_CustomMissile("DTP",31,11,frandom(-1,1),CMF_OFFSETPITCH,frandom(-1,1));
			A_AlertMonsters(0,AMF_TARGETEMITTER);
			invoker.PrimAmmo--;
		}
	}
	
	States
	{
		Spawn:
			PRAI E 1 A_Look;
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		See:
			PRAI AAAAAABBBBBB 1
			{
				If (Master && Distance3D(master) < 70 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			PRAI CCCCCCDDDDDD 1
			{
				If (Master && Distance3D(master) < 128 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		Stand:
			PRAI E 0; //A_JumpIf(random(1,10) > 2, "RealStand");
		RealStand:
			PRAI E 1
			{ 
				If (IdleTic >= 350)
				{
					IdleTic = 0;
					A_StartSound("Marine/EnergySee", CHAN_VOICE);
				}
				IdleTic++;
				if(random(1,20) <= 3)
				{
					A_SetAngle(angle + random(-25,25));
				}
				A_Chase(Null,"Missile",CHF_NOPLAYACTIVE|CHF_DONTMOVE|CHF_NODIRECTIONTURN);
			}
			Goto See;
		TeleTic:
			TNT1 A 0 
			{
				if (teletic >= 15)
				{
					A_ClearTarget();
					teletic = 0;
					Warp(master, frandom(-16, -64), frandom(-64, 64), 0, 0, WARPF_STOP|WARPF_TOFLOOR);
				}
				teletic++;
			}
			Goto See;
		Melee:
			TNT1 A 0 A_JumpIf(SecAmmo <= 0, "Reload2");
			TNT1 A 0 A_Recoil(2);
			PRAI E random(1,4) A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			PRAI F 1 Bright Light("Playgunlight")
			{
				IdleTic = 0;
				DTechRifleMarine_Fire(true);
				A_ChangeVelocity(random(-1,-5), random(-3,3), random(1,2),CVF_RELATIVE);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			PRAI E 2;
			TNT1 A 0 A_Jump(128,"Melee");
			Goto See;
		
		Missile:
			TNT1 A 0 A_JumpIf(PrimAmmo <= 0, "Reload");
			TNT1 A 0
			{
				if(!SetIdle && random(1,5))
				{
					A_ChangeVelocity(random(2,4), random(-4,4), random(1,2),CVF_RELATIVE);
				}
			}
		Missile1:
			PRAI E 1 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			PRAI F 2 Bright Light("ZombieDemonTech")
			{
				IdleTic = 0;
				DTechRifleMarine_Fire(false);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			PRAI E 2 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			TNT1 A 0 A_JumpIf(target && target.health <= 0, "Missile1End");
			TNT1 A 0 A_Jump(224,"Missile1");
		Missile1End:
			PRAI E 10 A_StartSound("Weapons/DTRVent", 0);
			Goto See;
			
		
		Reload:
			PRAI E 2;
			PRAI A 8;
			PRAI A 2 A_StartSound("Weapons/DTRMagout", 0);
			PRAI A 32 A_StartSound("Weapons/DTRVent", 0);
			PRAI A 10
			{
				A_StartSound("Weapons/DTRLoad", 0);
				PrimAmmo = 60;
			}
			PRAI A 4 A_StartSound("Weapons/DTRMagin", 0);
			PRAI E 2;
			Goto See;
		Reload2:
			PRAI E 2;
			PRAI E 20 A_StartSound("Pistol/out", 0);
			PRAI E 16 A_StartSound("Pistol/in", 0);
			PRAI E 8 A_StartSound("Pistol/cock", 0);
			PRAI E 8 A_StartSound("Pistol/release", 0);
			PRAI A 2;
			TNT1 A 0 { SecAmmo = 15;}
			Goto See;
			
		Pain:
			PRAI G 8
			{
				A_Pain();
				A_ChangeVelocity(random(-5,5), random(-5,5), random(1,2),CVF_RELATIVE);
			}
			Goto See;
		Death:
		FakeDeath:
			PRAI H 4 Marine_DropGoodies();
			PRAI I 4 A_PlayerScream();
			PRAI JKL 4;
			TNT1 A 0
			{
				if(GetCvar("Spooks_nothuds")==1)
				{ A_playsound("body/crash",7); }
			}
			PRAI M 4;
			PRAI N -1;
			Stop;
			
		FakeRaise:
			TNT1 A 0 
			{
				A_StartSound("death/rewind", CHAN_VOICE);
			}
			PRAI NMLKJIHG 4;
			Goto See;
		XDeath:
			TNT1 A 0 
			{
				Marine_DropGoodies();
				Gibbed = true;
			}
			TNT1 AA 0 A_CustomMissile("RedBloodCloud", random(25,50), 0, random(0,360), 2, random(0,360));
			PRAI P 3 A_XScream();
			PRAI Q 3 A_NoBlocking();
			PRAI R 3;
			TNT1 A 0 A_playsound("body/crash",7);
			PRAI STUV 3;
			PRAI W -1;
			Stop;
    }
}