class PCQSGMarine : Follower_Marine
{	
	Default
	{
		Tag "QSG Marine";
		
		Translation "112:127=80:111";
		
		DeathSound "Marine/ShotgunDeath";
		Painsound "Marine/ShotgunPain";
		Seesound "Marine/ShotgunSee";
		
		DamageFactor "FriendMarineDamage", 0;
	}
	
	Override Void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		PrimAmmo = 4;
		SecAmmo = 15;
		
		A_StartSound("Marine/ShotgunSee",CHAN_VOICE);
	}
	
	override void Tick() 
	{
		super.Tick();
		
		if (isFrozen())
		{
			return;
		}
		/*
		if(!master)
		{
			Spawn("TeleportFog", (pos.x, pos.y, pos.z + height * 0.5));
			Destroy();
			return;
		}*/
		
		if(health < default.health && HealTimer <= 0)
		{
			if(random(1,20) == 3) { A_Pain(); }
			switch(random(1,3))
			{
				default:
				case 1:
					A_StartSound("Pickup/flaskuse",0);
					A_SetHealth(health + 5);
					break;
				case 2:
					A_StartSound("Pickups/Pstimuse",0);
					A_SetHealth(health + 15);
					break;
				case 3:
					A_StartSound("Pickup/pmeduse",0);
					A_SetHealth(health + 25);
					break;
			}
			HealTimer = random(70,140);
		}
		
		if (health <= 5 && !Gibbed && !InStateSequence(curstate, FindState("FakeDeath")))
		{
			A_SetHealth(default.health);
			SetStateLabel("FakeDeath");
		}
		
		if(health <= default.health / 2 && target != master) { bFRIGHTENED = true; }
		else { bFRIGHTENED = false; }
		
		HealTimer--;
	}
	
	Override bool CanCollideWith(Actor other, bool Passive)
	{
		If(!Other) 
		Return False;
		If(Other && !Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}			
			Return True;
		}
		If(Other && Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}
			Return True;
		}
		Return True;
	}
	
	override bool Used(Actor user)
	{
		let plr = PCMarine(user);
		
		master = user;
		
		if(InStateSequence(curstate, FindState("FakeDeath")))
		{
			//[Pop] Maybe spawn particles or something
			SetStateLabel("FakeRaise");
		}
		else
		{
			SetIdle = !SetIdle;
			if(SetIdle) { A_StartSound("Marine/ShotgunSee",CHAN_VOICE); }
			else { A_StartSound("Marine/ShotgunSee",CHAN_VOICE); }
			//[Pop] Invert This basically
		}
		
		return Super.Used(user);
	}
	
	action void QSGMarine_Fire(bool which, bool both)
	{	
		if(which)
		{
			A_StartSound("zombie/PistolFire", 0, CHANF_OVERLAP, 0.85);
			A_CustomMissile("Marinetracer",28,9,frandom(-2,2),CMF_OFFSETPITCH,frandom(-1,1));
			A_SpawnItemEx("PistolCasing", 12, 6, 30, Random(2, 6), 0, Random(1, 3), Random(-80, -90), 128);
			A_AlertMonsters(0,AMF_TARGETEMITTER);
			invoker.SecAmmo--;
		}
		else
		{
			if(both)
			{
				A_StartSound("weapons/Quadnormfire", 0, CHANF_OVERLAP, 1, ATTN_NORM);
				for(int i=32;i>0;i--) { A_CustomMissile("Marinetracer",28,9,frandom(-5,5),CMF_OFFSETPITCH,frandom(-4,4)); }
				A_AlertMonsters(0,AMF_TARGETEMITTER);
				invoker.PrimAmmo-=4;
			}
			else
			{
				A_StartSound("Weapons/Quadaltfire", 0, CHANF_OVERLAP, 1, ATTN_NORM);
				for(int i=16;i>0;i--) { A_CustomMissile("Marinetracer",28,9,frandom(-5,5),CMF_OFFSETPITCH,frandom(-4,4)); }
				A_AlertMonsters(0,AMF_TARGETEMITTER);
				invoker.PrimAmmo-=2;
			}
		}
	}
	
	States
	{
		Spawn:
			PQST E 1 A_Look;
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		See:
			PQST AAAAAABBBBBB 1
			{
				If (Master && Distance3D(master) < 70 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			PQST CCCCCCDDDDDD 1
			{
				If (Master && Distance3D(master) < 128 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		Stand:
			PQST E 0; //A_JumpIf(random(1,10) > 2, "RealStand");
		RealStand:
			PQST E 1
			{ 
				If (IdleTic >= 350)
				{
					IdleTic = 0;
					A_StartSound("Marine/ShotgunSee", CHAN_VOICE);
				}
				IdleTic++;
				if(random(1,20) <= 3)
				{
					A_SetAngle(angle + random(-25,25));
				}
				A_Chase(Null,"Missile",CHF_NOPLAYACTIVE|CHF_DONTMOVE|CHF_NODIRECTIONTURN);
			}
			Goto See;
		TeleTic:
			TNT1 A 0 
			{
				if (teletic >= 15)
				{
					A_ClearTarget();
					teletic = 0;
					Warp(master, frandom(-16, -64), frandom(-64, 64), 0, 0, WARPF_STOP|WARPF_TOFLOOR);
				}
				teletic++;
			}
			Goto See;
		Melee:
			TNT1 A 0 A_JumpIf(SecAmmo <= 0, "Reload2");
			TNT1 A 0 A_Recoil(2);
			PQST E random(1,4) A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			PQST F 1 Bright Light("Playgunlight")
			{
				IdleTic = 0;
				QSGMarine_Fire(true, false);
				A_ChangeVelocity(random(-1,-5), random(-3,3), random(1,2),CVF_RELATIVE);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			PQST E 2;
			TNT1 A 0 A_Jump(128,"Melee");
			Goto See;
		
		Missile:
			TNT1 A 0 A_JumpIf(PrimAmmo <= 0, "Reload");
			TNT1 A 0
			{
				if(!SetIdle)
				{
					A_ChangeVelocity(random(2,10), random(-10,10), random(1,2),CVF_RELATIVE);
				}
			}
			TNT1 A 0 A_Jump(256, "Missile1", "Missile2");
		Missile1:
			TNT1 A 0 A_JumpIf(PrimAmmo < 2, "Reload");
			PQST E random(8,24) A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			PQST F 2 Bright Light("Playgunlight")
			{
				IdleTic = 0;
				QSGMarine_Fire(false, true);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			PQST E 4;
			TNT1 A 0 A_Jump(128,"Reload");
			Goto See;
		Missile2:
			TNT1 A 0 A_JumpIf(PrimAmmo == 0, "Reload");
			PQST E random(6,18) A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			PQST F 2 Bright Light("Playgunlight")
			{
				IdleTic = 0;
				QSGMarine_Fire(false, false);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			PQST E 4;
			TNT1 A 0 A_Jump(128,"Reload","Missile2");
			Goto See;
			
		
		Reload:
			PQST E 2;
			PQST A 4;
			PQST A 24
			{
				A_StartSound("Weapons/Quadopen", 0);
				
				for(int i=4;i>PrimAmmo;i--) { A_SpawnItemEx("Spentshell", -8, 6, 36, Random(2, 6), 0, Random(1, 3), Random(-80, -90), 128); }
			}
			PQST A 16
			{
				A_StartSound("Weapons/Quadload", 0);
				PrimAmmo+=2;
			}
			PQST A 16
			{
				A_StartSound("Weapons/Quadload", 0);
				PrimAmmo+=2;
			}
			PQST A 12 A_StartSound("Weapons/Quadclose", 0); 
			PQST AE 6;
			Goto See;
		Reload2:
			PQST E 2;
			PQST E 20 A_StartSound("Pistol/out", 0);
			PQST E 16 A_StartSound("Pistol/in", 0);
			PQST E 8 A_StartSound("Pistol/cock", 0);
			PQST E 8 A_StartSound("Pistol/release", 0);
			PQST A 2;
			TNT1 A 0 { SecAmmo = 15;}
			Goto See;
			
		Pain:
			PQST G 8
			{
				A_Pain();
				A_ChangeVelocity(random(-5,5), random(-5,5), random(1,2),CVF_RELATIVE);
			}
			Goto See;
		Death:
		FakeDeath:
			PQST H 4 Marine_DropGoodies();
			PQST I 4 A_PlayerScream();
			PQST JKL 4;
			TNT1 A 0
			{
				if(GetCvar("Spooks_nothuds")==1)
				{ A_playsound("body/crash",7); }
			}
			PQST M 4;
			PQST N -1;
			Stop;
			
		FakeRaise:
			TNT1 A 0 
			{
				A_StartSound("death/rewind", CHAN_VOICE);
			}
			PQST NMLKJIHG 4;
			Goto See;
		XDeath:
			TNT1 A 0 
			{
				Marine_DropGoodies();
				Gibbed = true;
			}
			TNT1 AA 0 A_CustomMissile("RedBloodCloud", random(25,50), 0, random(0,360), 2, random(0,360));
			PQST P 3 A_XScream();
			PQST Q 3 A_NoBlocking();
			PQST R 3;
			TNT1 A 0 A_playsound("body/crash",7);
			PQST STUV 3;
			PQST W -1;
			Stop;
    }
}