class PCShotgunMarine : Follower_Marine
{
	Int TeleTic;	
	Int	IdleTic;
	Int HealTimer;
	
	Int PrimAmmo;
	Int SecAmmo;
	
	bool SecondaryOut;
	bool SetIdle;
	
	bool Gibbed;
	
	Default
	{
		DeathSound "Marine/ShotgunDeath";
		Painsound "Marine/ShotgunPain";
		Seesound "Marine/ShotgunSee";
		
		DamageFactor "FriendMarineDamage", 0;
	}
	
	override int TakeSpecialDamage(Actor inflictor, Actor source, int damage, Name damagetype)
	{
		if (source && (source.player || source is "Follower_Marine"))
		{
			return 0;
		}
		return super.TakeSpecialDamage(inflictor, source, damage, damagetype);
	}
	
	Override Void PostBeginPlay()
	{
		Super.PostBeginPlay();
		
		SecondaryOut = false;
		SetIdle = false;
		HealTimer = 0;
		
		Gibbed = false;
		
		PrimAmmo = 10;
		SecAmmo = 15;
		
		A_GiveInventory("IMAFRIENDLYDIPSHIT");
		
		A_StartSound("Marine/ShotgunSee",CHAN_VOICE);
	}
	
	override void Tick() 
	{
		super.Tick();
		
		if (isFrozen())
		{
			return;
		}
		/*
		if(!master)
		{
			Spawn("TeleportFog", (pos.x, pos.y, pos.z + height * 0.5));
			Destroy();
			return;
		}*/
		
		if(health < default.health && HealTimer <= 0)
		{
			if(random(1,20) == 3) { A_Pain(); }
			switch(random(1,3))
			{
				default:
				case 1:
					A_StartSound("Pickup/flaskuse",0);
					A_SetHealth(health + 5);
					break;
				case 2:
					A_StartSound("Pickups/Pstimuse",0);
					A_SetHealth(health + 15);
					break;
				case 3:
					A_StartSound("Pickup/pmeduse",0);
					A_SetHealth(health + 25);
					break;
			}
			HealTimer = random(70,140);
		}
		
		if (health <= 5 && !Gibbed && !InStateSequence(curstate, FindState("FakeDeath")))
		{
			A_SetHealth(default.health);
			SetStateLabel("FakeDeath");
		}
		
		if(health <= default.health / 2 && target != master) { bFRIGHTENED = true; }
		else { bFRIGHTENED = false; }
		
		HealTimer--;
	}
	
	Override bool CanCollideWith(Actor other, bool Passive)
	{
		If(!Other) 
		Return False;
		If(Other && !Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}			
			Return True;
		}
		If(Other && Passive)
		{
			If(Other.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other == Master) 
				Return False;
			}			
			If(Other.bMISSILE && Other.Target && Other.Target.Player)
			{
				If(!Deathmatch) 
				Return False;
				Else If(Deathmatch && Other.Target == Master) 
				Return False;
			}
			Return True;
		}
		Return True;
	}
	
	override bool Used(Actor user)
	{
		let plr = PCMarine(user);
		
		master = user;
		
		if(InStateSequence(curstate, FindState("FakeDeath")))
		{
			//[Pop] Maybe spawn particles or something
			SetStateLabel("FakeRaise");
		}
		else
		{
			SetIdle = !SetIdle;
			if(SetIdle) { A_StartSound("Marine/ShotgunSee",CHAN_VOICE); }
			else { A_StartSound("Marine/ShotgunSee",CHAN_VOICE); }
			//[Pop] Invert This basically
		}
		
		return Super.Used(user);
	}
	
	action void ShotgunMarine_Fire(bool which)
	{	
		if(which)
		{
			A_StartSound("zombie/PistolFire", 0, CHANF_OVERLAP, 0.85);
			A_CustomMissile("Marinetracer",28,9,frandom(-2,2),CMF_OFFSETPITCH,frandom(-1,1));
			A_AlertMonsters(0,AMF_TARGETEMITTER);
			invoker.SecAmmo--;
		}
		else
		{
			A_StartSound("Zombie/Pumpfire", 0, CHANF_OVERLAP, 1, ATTN_NORM);
			for(int i=8;i>0;i--) { A_CustomMissile("Marinetracer",28,9,frandom(-5,5),CMF_OFFSETPITCH,frandom(-4,4)); }
			A_AlertMonsters(0,AMF_TARGETEMITTER);
			invoker.PrimAmmo--;
		}
	}
	
	States
	{
		Spawn:
			PLA3 E 1 A_Look;
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		See:
			PLA3 AAAAAABBBBBB 1
			{
				If (Master && Distance3D(master) < 70 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			PLA3 CCCCCCDDDDDD 1
			{
				If (Master && Distance3D(master) < 128 || SetIdle)
				{
					Return ResolveState("Stand");
				}
				A_Chase();
				A_Recoil(-0.25);
				Return ResolveState(Null);
			}
			TNT1 A 0 A_StartSound("step/hard",0);
			TNT1 A 0 A_CheckSight("TeleTic");
			Loop;
		Stand:
			PLA3 E 0; //A_JumpIf(random(1,10) > 2, "RealStand");
		RealStand:
			PLA3 E 1
			{ 
				If (IdleTic >= 350)
				{
					IdleTic = 0;
					A_StartSound("Marine/ShotgunSee", CHAN_VOICE);
				}
				IdleTic++;
				if(random(1,20) <= 3)
				{
					A_SetAngle(angle + random(-25,25));
				}
				A_Chase(Null,"Missile",CHF_NOPLAYACTIVE|CHF_DONTMOVE|CHF_NODIRECTIONTURN);
			}
			Goto See;
		TeleTic:
			TNT1 A 0 
			{
				if (teletic >= 15)
				{
					A_ClearTarget();
					teletic = 0;
					Warp(master, frandom(-16, -64), frandom(-64, 64), 0, 0, WARPF_STOP|WARPF_TOFLOOR);
				}
				teletic++;
			}
			Goto See;
		Melee:
			TNT1 A 0 A_JumpIf(SecAmmo <= 0, "Reload2");
			TNT1 A 0 A_Recoil(2);
			PLA3 E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			PLA3 F 1 Bright Light("Playgunlight")
			{
				IdleTic = 0;
				ShotgunMarine_Fire(true);
				A_ChangeVelocity(random(-1,-5), random(-3,3), random(1,2),CVF_RELATIVE);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			PLA3 E 2;
			TNT1 A 0 A_Jump(128,"Melee");
			Goto See;
		
		Missile:
			TNT1 A 0 A_JumpIf(PrimAmmo <= 0, "Reload");
			TNT1 A 0
			{
				if(!SetIdle)
				{
					A_ChangeVelocity(random(2,10), random(-10,10), random(1,2),CVF_RELATIVE);
				}
			}
			PLA3 E 4 A_FaceTarget(0,90,0,0, FAF_MIDDLE);
			PLA3 F 2 Bright Light("Playgunlight")
			{
				IdleTic = 0;
				ShotgunMarine_Fire(false);
				A_Chase(NULL,NULL,CHF_FASTCHASE);
			}
			PLA3 E 12;
			PLA3 A 12 A_StartSound("Zombie/cock", 0);
			PLA3 A 12 A_SpawnItemEx("Spentshell", -8, 0, 30, Random(2, 6), 0, Random(1, 3), Random(-80, -90), 128);
			PLA3 E 8;
			TNT1 A 0 A_Jump(128,"Missile");
			Goto See;
			
		
		Reload:
			PLA3 E 2;
			PLA3 A 4;
			PLA3 A 16 A_StartSound("Weapons/PUMPB", 0);
			PLA3 A 10
			{
				A_StartSound("Weapons/Shotgun/Load", 0);
				PrimAmmo++;
			}
			PLA3 A 16 A_StartSound("Weapons/PUMPF", 0);
			PLA3 A 2;
		ReloadLoop:
			PLA3 A 2;
			PLA3 A 12
			{
				A_StartSound("Weapons/Shotgun/Load", 0);
				PrimAmmo++;
			}
			PLA3 A 2;
			TNT1 A 0 A_JumpIf(PrimAmmo < 10, "ReloadLoop");
			PLA3 AE 6;
			Goto See;
		Reload2:
			PLA3 E 2;
			PLA3 E 20 A_StartSound("Pistol/out", 0);
			PLA3 E 16 A_StartSound("Pistol/in", 0);
			PLA3 E 8 A_StartSound("Pistol/cock", 0);
			PLA3 E 8 A_StartSound("Pistol/release", 0);
			PLA3 A 2;
			TNT1 A 0 { SecAmmo = 15;}
			Goto See;
			
		Pain:
			PLA3 G 8
			{
				A_Pain();
				A_ChangeVelocity(random(-5,5), random(-5,5), random(1,2),CVF_RELATIVE);
			}
			Goto See;
		Death:
		FakeDeath:
			PLA3 H 4 Marine_DropGoodies();
			PLA3 I 4 A_PlayerScream();
			PLA3 JKL 4;
			TNT1 A 0
			{
				if(GetCvar("Spooks_nothuds")==1)
				{ A_playsound("body/crash",7); }
			}
			PLA3 M 4;
			PLA3 N -1;
			Stop;
			
		FakeRaise:
			TNT1 A 0 
			{
				A_StartSound("death/rewind", CHAN_VOICE);
			}
			PLA3 NMLKJIHG 4;
			Goto See;
		XDeath:
			TNT1 AA 0 A_CustomMissile("RedBloodCloud", random(25,50), 0, random(0,360), 2, random(0,360));
			TNT1 A 0 
			{
				Marine_DropGoodies();
				Gibbed = true;
			}
			PLA3 P 3 A_XScream();
			PLA3 Q 3 A_NoBlocking();
			PLA3 R 3;
			TNT1 A 0 A_playsound("body/crash",7);
			PLA3 STUV 3;
			PLA3 W -1;
			Stop;
    }
}