class Bombpotats : Actor
{
	Default
	{
		Obituary "%o tripped on %k's grenade.";
		seesound "weapons/grenadelob";
		deathsound "weapons/grenboom";
		Scale 0.4;
		height 4;
		radius 4;
		Damage (30);
		speed 30;
		mass 50;
		Gravity .65;
		WallBounceFactor .25;
		bouncecount 3;
		bouncefactor 0.45;
		PROJECTILE;
		+Doombounce;
		-FLOORHUGGER;
		-NOGRAVITY;
		 -NOTELEPORT;
		+ACTIVATEIMPACT;
		+ACTIVATEPCROSS;
		+CANBOUNCEWATER;
		+MTHRUSPECIES;
		-BOUNCEONACTORS;
		+ROLLSPRITE;
		+ROLLCENTER;
		Species "Player";
		Damagetype "PlayerExplosive";
	}

	states
	{
		Spawn:
			TNT1 A 0 ThrustThingZ(0,5,0,1);
			HGND AAAAAAAAAAAAAAA 3 A_SetRoll(roll-45, SPF_INTERPOLATE);
			loop;
		Death:
			TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
			TNT1 AAA 0 A_SpawnProjectile("Smallerkaboom",0,0,FRandom(0,360),2,FRandom(0,360));
			TNT1 A 1 
			{
				A_AlertMonsters();
				A_SpawnItemEx("OrangeParticleSpawner",0,0,0,0,0,0,0,128);
				A_SpawnItem("RocketEx");
				A_Explode(140,120,0,1,100,0,0,"apuff","HGboom");
				A_Explode(60,120,1,1,100,0,0,"apuff","HGboom");
				Radius_Quake(1,8,0,28,0);
			}
			TNT1 AAAA 0 
			{
				A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
				A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			}
			TNT1 AAAAA 5 A_SpawnItemEx("SmokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
			Stop;
		LessExplode:
			TNT1 A 1 
			{
				A_AlertMonsters();
				A_SpawnItem("RocketEx");
				A_Explode(140,120,0,1,100,0,0,"apuff","HGboom");
				A_Explode(60,120,1,1,100,0,0,"apuff","HGboom");
				Radius_Quake(1,8,0,28,0);
			}
			Stop;
	}
}

//Mines
class Tossedmine : Actor
{
	Default
	{
		Scale 0.85;
		Radius 10;
		Height 12;
		Speed 20;
		//Damage (10);
		Mass 20;
		SeeSound "weapons/minebounce";
		Species "Mines";
		+MISSILE;
		+DONTTHRUST;
		+THRUSPECIES;
		+CANBOUNCEWATER;
		+HEXENBOUNCE;
		-NOTELEPORT;
		+BOUNCEONACTORS;
		+DROPOFF;
		+MTHRUSPECIES;
		BounceCount 3;
		BounceFactor 0.18;
		WallBounceFactor 0.22;
	}

	States
	{
		Spawn:
			TNT1 A 0 nodelay A_StopSound;
			Goto Thrown;
		Thrown:
			LMIN A 30;
			LMIN B 10 Bright;
			Loop;
		Death:
			LMIN A 35;
			LMIN A 1 A_SpawnItem("Agitatedmine");
			Stop;
	}
}

class Agitatedmine : CustomInventory
{
	Default
	{
		Scale 0.85;
		Radius 20;
		Height 12;
		Damage (0);
		Health 7;
		Mass 20;
		Species "Mines";
		Damagetype "PlayerExplosive";
		Inventory.Pickupmessage "[-] \c[darkgray]Land mine\c- picked up. (+1 Mine)";
		Inventory.PickupSound "weapons/minepickup";
		+DONTTHRUST;
		-MISSILE;
		+FIXMAPTHINGPOS;
		+THRUSPECIES;
		+MTHRUSPECIES;
		+MOVEWITHSECTOR;
		+NOBLOOD;
		+SHOOTABLE;
		+Touchy;
	}

	States
	{
		Spawn:
			LMIN A 25 A_ChangeLinkFlags(1);
			LMIN B 10 Bright Light("MineLight1")
			{
				A_startsound("Weapons/MIB",31,0);
				A_ChangeLinkFlags(0);
			}
			Loop;
		Pickup:
			TNT1 A 0 A_giveinventory("Mineammo",1);
			Stop;
		Death:
			TNT1 A 0 A_Die;
		Explode:
			TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
			LMIN B 15 Bright A_startsound("Weapons/minebeep",41);
			TNT1 AAAA 0 A_SpawnProjectile("SmallKaboom",10,0,FRandom(0,360),2,FRandom(20,160));
			TNT1 AAAAAAAA 0 A_SpawnItemEx("MineExSpark",0,0,10,FRandom(6,-6),FRandom(6,-6),FRandom(8,12));
			TNT1 A 1 
			{
				A_AlertMonsters();
				A_startsound("weapons/mineboom",52,0,1);
				A_SpawnItemEx("OrangeParticleSpawner",0,0,0,0,0,0,0,128);
				A_SpawnItem("Mineex");
				A_Explode(140,140,0,1,120,0,0,"apuff","HGboom");
				A_Explode(60,140,1,1,120,0,0,"apuff","HGboom");
				Radius_Quake(1,8,0,28,0);
			}
			TNT1 A 0 A_Explode(140,140,0,1,1,0,0,"apuff","Mineboom");
			TNT1 A 0 A_Explode(60,140,1,1,1,0,0,"apuff","Mineboom");
			TNT1 A 0 Radius_quake(2,8,0,10,0);
			TNT1 A 0 Radius_Quake(1,8,0,28,0);
			TNT1 AAAA 0 
			{
				A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
				A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			}
			TNT1 AAAAA 5 A_SpawnItemEx("SmokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
			Stop;
		   LessExplode:
			LMIN B 15 Bright A_startsound("Weapons/minebeep",41);
			TNT1 A 0
			{
				A_AlertMonsters();
				A_startsound("Weapons/mineexplode",52);
			}
			TNT1 A 1 
			{
				A_SpawnItemEx("MineEx",0,0,0,0,0,0,0,128);
				A_Explode(140,140,0,1,120,0,0,"apuff","HGboom");
				A_Explode(60,140,1,1,120,0,0,"apuff","HGboom");
				Radius_quake(2,8,0,10,0);
				Radius_Quake(1,8,0,28,0);
			}
			Stop;
    }
}