class Justagrenade : Actor
{
	Default
	{
	  Radius 6;
	  Height 6;
	  Speed 30;
	  Damage (100);
	  Species "Player";
	  Scale 0.55;
	  Projectile;
	  -NOTELEPORT;
	  +DONTSPLASH;
	  +MTHRUSPECIES;
	  -NOGRAVITY;
	  -GRENADETRAIL;
	  -ROCKETTRAIL;
	  +SKYEXPLODE;
	  +CANBOUNCEWATER;
	  Gravity 0.4;
	  Obituary "%o successfully played catch with %k's Grenade.";
	  SeeSound "Weapons/GrenadeBounce";
	  DeathSound "Weapons/GLBoom";
	  Damagetype "Grenade";
	  Decal "Rocketscorch";
	}
  States
  {
	  Spawn:
		TNT1 A 0;
		TNT1 A 0 A_StopSound;
	  SpawnLoop:
		GBPJ ABCDEFG 1 A_CustomMissile("Missiletrailsmoke",Random(-1,1),Random(-1,1));
		Loop;
	  Death:
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 AAA 0 a_custommissile("SmallKaboom", 0, 0, random(0,360), 2, random(0,360));
		TNT1 A 0 
			{
			A_AlertMonsters();
			A_SpawnItemEx("OrangeParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
			A_SpawnItem("RocketEx");
			A_Explode(80,120,1,1,100,0,0,"Apuff","Grenadeboom");
			Radius_quake(3,8,0,10,0);
			Radius_Quake(1,8,0,28,0);
			}
		TNT1 A 0 
			{	
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),0,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),22,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),45,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),67,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),90,SXF_TRANSFERPOINTERS);
			
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),102,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),135,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),157,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),180,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),202,SXF_TRANSFERPOINTERS);

			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),225,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),250,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),270,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),290,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),315,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),337,SXF_TRANSFERPOINTERS);
			}
		TNT1 AAAA 0 
			{
			A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			}
		TNT1 AAAAA 5 A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
		Stop;
	LessExplode:
		TNT1 A 1
			{
			A_AlertMonsters();
			A_SpawnItem("RocketEx");
			A_Explode(80,120,1,1,100,0,0,"Apuff","Grenadeboom");
			Radius_quake(3,8,0,10,0);
			Radius_Quake(1,8,0,28,0);
			}
		TNT1 A 0 
			{	
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),0,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),22,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),45,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),67,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),90,SXF_TRANSFERPOINTERS);
			
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),102,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),135,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),157,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),180,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),202,SXF_TRANSFERPOINTERS);

			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),225,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),250,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),270,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),290,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),315,SXF_TRANSFERPOINTERS);
			A_SpawnItemEx("clusterbomb",0,0,0,10,frandom(1,-1),frandom(4,6),337,SXF_TRANSFERPOINTERS);
			}
		Stop;
    }
}

class Justagrenade2 : Justagrenade
{
	Default
	{
	  Radius 6;
	  Height 6;
	  Speed 30;
	  Damage(160);
	  Species "Player";
	  Scale 0.75;
	  Projectile;
	  +DOOMBOUNCE;
	  +CANBOUNCEWATER;
	  -NOTELEPORT;
	  +DONTSPLASH;
	  +MTHRUSPECIES;
	  -NOGRAVITY;
	  -GRENADETRAIL;
	  -ROCKETTRAIL;
	  +SKYEXPLODE;
	  Gravity 0.4;
	  WallBounceFactor 0.25;
	  BounceFactor 0.36;
	  SeeSound "Weapons/GrenadeBounce";
	  DeathSound "rocket/boom";
	  Damagetype "Grenade";
	}
}

class Clusterbomb : Justagrenade2
{
	Default
	{
		Radius 3;
		Height 3;
		Speed 20;
		Damage (1);
		Scale 0.8;
		Gravity 0.3;
		Damagetype "bomblet";
		species "Player";
		WallBounceFactor 0.25;
		BounceFactor 0.36;
		+THRUACTORS;
		+DOOMBOUNCE;
		-NOEXTREMEDEATH;
		+Doombounce;
	}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_StopSound;
	Cont:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128,6,12,18,24);
		TCGN AAAAAAAAAAAAAAAAAAAAAAAAA 1 A_CustomMissile("Minesparktrail",FRandom(-1,1),FRandom(-1,1));
	Death:
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 AAA 0 A_spawnitemex("smallkaboom",0,random(15,-15),random(15,-15));
		TNT1 A 1 
			{
			A_SpawnItem("ClusterEx");
			A_startsound("Weapons/clusterboom",90,CHANF_Overlap,1);
			A_Explode(82,74,1,1,54,0,0,"Apuff","Clusterboom");
			}
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner",0,0,0,0,0,0,0,128);
		TNT1 AA 0 A_CustomMissile("KindasmallKaboom",0,0,FRandom(0,360),2,FRandom(0,360));
		TNT1 AA 0 
			{
			A_CustomMissile("SmokeFX4",0,0,FRandom(0,360),2,FRandom(0,360));
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			}
		Stop;
	Lessexplode:
		TNT1 A 1 
			{
			A_SpawnItem("ClusterEx");
			A_startsound("Weapons/clusterboom",90,CHANF_Overlap,1);
			A_Explode(52,74,1,1,1,0,0,"Apuff","Clusterboom");
			}
		Stop;
		}
}

class CyberCB : Clusterbomb
{
	Default
	{
		Damagetype "Cyberrocket";
		-forceradiusdmg;
		+THRUGHOST;
	}
States
{
	Death:
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 A 1 
		{
		A_SpawnItem("ClusterEx");
		A_startsound("Weapons/clusterboom",90);
		A_Explode(42,44,0,0,24,0,0,"Apuff","Cyberrocket");
		}
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner",0,0,0,0,0,0,0,128);
		TNT1 AA 0 A_spawnitemex("kindasmallkaboom",0,random(15,-15),random(15,-15));
		TNT1 AA 0 
			{
			A_CustomMissile("SmokeFX4",0,0,FRandom(0,360),2,FRandom(0,360));
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			}
		Stop;
	Lessexplode:
		TNT1 A 1 
		{
		A_SpawnItem("ClusterEx");
		A_startsound("Weapons/clusterboom",90);
		A_Explode(42,44,0,0,24,0,0,"Apuff","Cyberrocket");
		}
		Stop;
		}
}

class ThrownPipebombs : Actor
{
	int user_exploded;

	Default
	{
		Projectile;
		Radius 6;
		Height 6;
		Speed 30;
		Damage 0;
		scale 0.5;
		Gravity 0.8;
		DamageType "PipeExplosion";
		Alpha 256;
		Obituary "%o tripped over the pipebomb.";
		+MISSILE;
		+WINDTHRUST;
		-NOGRAVITY;
		+DOOMBOUNCE;
		-NOTELEPORT;
		-BOUNCEONACTORS;
		+DROPOFF;
		+DontHarmSpecies;
		+Thruspecies;
		+Mthruspecies;
		+CANBOUNCEWATER;
		+GHOST;
		-NOGRAVITY;
		+ROLLSPRITE;
		+ROLLCENTER;
		+movewithsector;
		Bouncesound "Weapon/Pipebounce";
		Wallbouncesound "Weapon/Pipebounce";
		Species "ThrownPipebombs";
		WallBounceFactor .5;
		bouncecount 3;
		BounceType "Doom";
		BounceFactor 0.45;
		Mass 2;
	}

	States
	{
	Spawn:
		PIPB BBBBBBBBBB 2
		{
			A_JumpIfInventory("GrenadeDetonator", 1, "MakeItExplode", AAPTR_TARGET);
			A_SetRoll(roll+20, SPF_INTERPOLATE);
		}
		PIPB CCCCC 2 Bright Light("MineLight1")
		{
			A_JumpIfInventory("GrenadeDetonator", 1, "MakeItExplode", AAPTR_TARGET);
			A_SetRoll(roll+20, SPF_INTERPOLATE);
		}
		Loop;
	Death:
		TNT1 A 0 A_JumpIfInventory("GrenadeDetonator", 1, "MakeItExplode", AAPTR_TARGET); //A_JumpIfInventory("Gokaboomnow",1,"MakeItExplode");
		TNT1 A 0 A_JumpIf(user_exploded == 1,2);
		TNT1 A 0 A_SpawnItemEx("Idlepipebomb",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
		stop;
	Death.goaway:
		TNT1 A 1;
		Stop;
	MakeItExplode:
		PIPB C 4
		{
			user_exploded = user_exploded + 1;
		}
		PIPB D 4 Bright Light("MineLight1");
		TNT1 A 0
		{
			A_stop();
			A_ChangeLinkFlags(1);
		}
		TNT1 A 0	A_startsound("rocket/boom",99,0,1);
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 AAAAAA 0 A_spawnitemex("smallkaboom",0,random(35,-35),random(35,-35));
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0
		{
			A_explode(300,100,1,1,0,0,0,"Apuff","C4");
			A_explode(200,200,1,1,0,0,0,"Apuff","C4");
			A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		}
		TNT1 A 0
		{
			Radius_quake(7,8,0,10,0);
			Radius_Quake(4,8,0,28,0);
			Radius_Quake(2,8,0,50,0);
		}
		TNT1 AAAA 0 
		{
			A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
		}
		TNT1 AAAAA 5 A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
		TNT1 A 0 A_die("Goaway");
		Stop;
	LessExplode:
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 
		{
			A_explode(300,100,1,1,0,0,0,"Apuff","C4");
			A_explode(200,200,1,1,0,0,0,"Apuff","C4");
			A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		}
		TNT1 A 0
		{
			Radius_quake(7,8,0,10,0);
			Radius_Quake(4,8,0,28,0);
			Radius_Quake(2,8,0,50,0);
		}
		TNT1 A 0 A_die("Goaway");
		Stop;
		}
}

class Idlepipebomb : CustomInventory
{
	Default
	{
	 scale 0.5;
	 radius 8;
	 height 4;
	+FORCEXYBILLBOARD;
	-BLOODSPLATTER;
	 Inventory.PickupMessage "[-] \c[darkgray]Pipebomb\c- picked up. (+1 Pipebomb)";
	 Obituary "%o tripped over the pipebomb.";
	 Inventory.PickupSound "Items/Pipes";
	 Species "ThrownPipebombs";
	 }

	 States
	{
	Spawn:
		PIPB BBBBBBBBBB 2 A_JumpIfInventory("GrenadeDetonator", 1, "MakeItExplode", AAPTR_TARGET); //A_JumpIfInventory("Gokaboomnow",1,"MakeItExplode");
		TNT1 A 0 A_Startsound("Weapons/C4beep",50,0);
		PIPB CCCCC 2 Bright Light("MineLight1") A_JumpIfInventory("GrenadeDetonator", 1, "MakeItExplode", AAPTR_TARGET); //A_JumpIfInventory("Gokaboomnow",1,"MakeItExplode");
		Loop;
	Pickup:
		TNT1 A 0 A_giveinventory("C4ammo",1);
		Stop;
	MakeItExplode:
		PIPB C 4;
		PIPB D 4 Bright Light("MineLight1");
		TNT1 A 0
		{
		A_stop();
		A_ChangeLinkFlags(1);
		}
		TNT1 A 0	A_startsound("rocket/boom",99,0,1);
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128);
		TNT1 AAAAAA 0 A_spawnitemex("smallkaboom",0,random(35,-35),random(35,-35));
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 
		{
		A_explode(300,100,1,1,0,0,0,"Apuff","C4");
		A_explode(200,200,1,1,0,0,0,"Apuff","C4");
		A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		}
		TNT1 A 0
		{
		Radius_quake(7,8,0,10,0);
		Radius_Quake(4,8,0,28,0);
		Radius_Quake(2,8,0,50,0);
		}
		TNT1 AAAA 0 
		{
		A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
		A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
		A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
		A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
		}
		TNT1 AAAAA 5 A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
		Stop;
	LessExplode:
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 
		{
		A_explode(300,100,1,1,0,0,0,"Apuff","C4");
		A_explode(200,200,1,1,0,0,0,"Apuff","C4");
		A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		}
		TNT1 A 0
		{
		Radius_quake(7,8,0,10,0);
		Radius_Quake(4,8,0,28,0);
		Radius_Quake(2,8,0,50,0);
		}
		Stop;
		}
}

class C4Kaboom : Actor
{
	Default
	{
		Radius 0;
		Height 0;
		Speed 0;
		Scale 0.5;
		Damagetype "C4";
		-NOGRAVITY;
		+DOOMBOUNCE;
		-NOTELEPORT;
		+DROPOFF;
		+DontHarmSpecies;
		+Thruspecies;
		+CANBOUNCEWATER;
		-NOGRAVITY;
		+movewithsector;
		Damagetype "Rocket/boom";
		Obituary "%o tripped over the pipebomb.";
	}
	States
	{
	Spawn:
		TNT1 A 0	Nodelay A_startsound("rocket/boom",99,0,1);
		TNT1 A 0 A_JumpIf(GetCvar("Spooks_Toastermode")==1, "Lessexplode");
		TNT1 A 0 A_SpawnItemEx("OrangeParticleSpawner", 0, 0, 0, 0, 0, 0, 0, 128); 
		TNT1 AAAAAA 0 A_spawnitemex("smallkaboom",0,random(35,-35),random(35,-35));
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 A_explode(300,100,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(200,200,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 Radius_quake(7,8,0,10,0);
		TNT1 A 0 Radius_Quake(4,8,0,28,0);
		TNT1 A 0 Radius_Quake(2,8,0,50,0);
		TNT1 AAAA 0
		{
			A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 0.1*random(2,5), 0.1*random(2,5), 0.1*random(2,5), random(0,360), 128, 0);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
			A_SpawnItemEx("Debris",0,0,0,FRandom(4,-4),FRandom(4,-4),FRandom(4,8),0,128);
		}
		TNT1 AAAAA 5 A_SpawnItemEx("smokeFX2", random(13,-13), random(13,-13), random(13,-13), 1*random(2,5), 1*random(2,5), 1*random(2,5), random(0,360), 128, 0);
		Stop;
	LessExplode:
		TNT1 A 1 A_SpawnItem("C4Ex");
		TNT1 A 0 A_explode(300,100,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(200,200,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 A_explode(100,300,1,1,0,0,0,"Apuff","C4");
		TNT1 A 0 Radius_quake(3,8,0,10,0);
		TNT1 A 0 Radius_Quake(1,8,0,28,0);
		Stop;
	}
}

Class GrenadeDetonator : Inventory
{
	Default
	{
		Inventory.MaxAmount 1;
	}
}

Class GLMode : Inventory
{
	Default
	{
		Inventory.MaxAmount 1;
	}
}

Class AmmoSwap1Loop : Inventory
{
	Default
	{
		Inventory.MaxAmount 1;
	}
}

class GLmag : Ammo
{
	Default
	{
	  Inventory.Amount 0;
	  Inventory.MaxAmount 4;
	  Ammo.BackpackAmount 0;
	  Ammo.BackpackMaxAmount 4;
	  Inventory.Icon "ROCKC0";
	  +INVENTORY.IGNORESKILL;
	}
}

class JustaBeegGL : JustaWeapon
{
	Default
		{
		Weapon.AmmoType1 "GLMag";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "Rockets";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 2;
		Obituary "%k didn't realized non-launched rockets were dangerous.";
		Inventory.PickupSound "weapons/shellslide";
		weapon.slotnumber 6;
		Weapon.SelectionOrder 2300;
		Weapon.SlotPriority 20;
		Scale 0.7;
		Inventory.AltHUDIcon "BGLPA0";
		Inventory.pickupmessage "[6] - \c[Rocketcolor]Grenade launcher\c- acquired. ";
		Tag "$PC_GRENADELAUNCHERTAG";
	}
	States
	{
		Spawn:
			BGLP A -1;
			Stop;
		Select: 
			BGLF ED 1 A_WeaponReady(WRF_NOFIRE);
			BGLF A 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect: 
			BGLF A 1;
			BGLF DE 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			BGLF A 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Zoom:
			BGLF A 2
			{
				if(CountInv("GLMode") == 1)
				{
					A_TakeInventory("GLMode", 1);
					A_startsound("Weapons/pipebutton",10);
				}
				else
				{
					A_GiveInventory("GLMode", 0);
					A_startsound("Weapons/pipebutton",10);
				}
			}
			TNT1 A 0 A_JumpIfInventory("GLMode", 1, "ZoomAmmoSwapC4");
			Goto ZoomAmmoSwapGL;
		ZoomAmmoSwapGL:
			TNT1 A 0 A_JumpifInventory("GLMag", 1, 1);
			Goto ZASGL1;
			TNT1 A 0 A_TakeInventory("GLMag", 1);
			TNT1 A 0 A_DropItem("C4Ammo");
			Loop;
		ZASGL1:
			TNT1 A 0 A_JumpifInventory("GLMag", 4, "ZoomEnd");
			TNT1 A 0 A_JumpIf(CountInv("Rockets") == 0, "ZoomEnd");
			TNT1 A 0 A_TakeInventory("Rockets", 1);
			TNT1 A 0 A_GiveInventory("GLMag", 1);
			Loop;
		ZoomAmmoSwapC4:
			TNT1 A 0 A_JumpifInventory("GLMag", 1, 1);
			Goto ZASC41;
			TNT1 A 0 A_TakeInventory("GLMag", 1);
			TNT1 A 0 A_DropItem("Rockets");
			Loop;
		ZASC41:
			TNT1 A 0 A_JumpifInventory("GLMag", 4, "ZoomEnd");
			TNT1 A 0 A_JumpIf(CountInv("C4Ammo") == 0, "ZoomEnd");
			TNT1 A 0 A_TakeInventory("C4Ammo", 1);
			TNT1 A 0 A_GiveInventory("GLMag", 1);
			Loop;
		ZoomEnd:
			BGLF A 10;
			Goto Ready;
		Dryfire:
			BGLF A 16 A_startsound("Weapons/Grenadeempty",11);
			BGLF A 4;
			Goto ready;
		Fire:
			TNT1 A 0 A_jumpifinventory("GLMag",1,1);
			goto Dryfire;
			BGLF B 2 BRIGHT 
					{
						A_GunFlash();
						A_ZoomFactor(0.999);
						If(CountInv("Power4xDamage"))
						{
							A_startsound("Weapons/quadfire",5);
						}
						If(CountInv("Chalicedamage"))
						{
							A_startsound("Weapons/quadfire",5);
						}				
						if(CountInv("GLMode") == 1)
						{
							A_FireCustomMissile("ThrownPipebombs",0,0,0,0,6.328125);
							A_startsound("Weapons/GLfire2",10,0,0.35);
							A_AlertMonsters(100);
						}
						else
						{
							A_FireCustomMissile("Justagrenade",0,0,0,0,0,6.328125);
							A_startsound("Weapons/GLfire",10);
							A_AlertMonsters();
						}
					}				
			TNT1 A 0 
				  {
				  if(CountInv("Guntoken") && random(1,5) == 5)
					{
						if(CountInv("GLMode") == 1)
						{
							A_FireCustomMissile("ThrownPipebombs",random(-5,5),0,0,0,0,6.328125);
						}
						else
						{
							A_FireCustomMissile("Justagrenade",random(-5,5),0,0,0,0,6.328125);
						}
						A_startsound("Gun/Proc",999,0,1);
					}
				  }
			TNT1 A 0 A_ZoomFactor(0.99,ZOOM_INSTANT);
			TNT1 A 0 
			 {
				if(CountInv("Ammotoken") && random(1,5) == 5) 
				{
					A_startsound("ammo/Proc",999,0,0.65);
				}
				else
				{
					A_Takeinventory("GLMag",1,TIF_NOTAKEINFINITE);
				}
			}
			BGLF C 2 bright A_SetPitch(pitch-2, SPF_INTERPOLATE);
			TNT1 A 0 A_FireCustomMissile("GSSpawner",0,0,0,8);
			TNT1 A 0 A_ZoomFactor(1.0);
			BGLF A 4;
			Goto Ready;
		AltFire2:
			TNT1 A 0 A_jumpifinventory("GLMag",1,1);
			goto Dryfire;
			BGLF B 2 BRIGHT 
					{
						A_GunFlash();
						A_ZoomFactor(0.999);
						If(CountInv("Power4xDamage"))
						{
							A_startsound("Weapons/quadfire",5);
						}
						If(CountInv("Chalicedamage"))
						{
							A_startsound("Weapons/quadfire",5);
						}
						A_FireCustomMissile("Justagrenade2",0,0,0,0,0,6.328125);
						A_startsound("Weapons/GLfire",10);
						A_AlertMonsters();
					}				
			TNT1 A 0 
				  {
				  if(CountInv("Guntoken") && random(1,5) == 5)
					{
						A_FireCustomMissile("Justagrenade2",random(-5,5),0,0,0,0,6.328125);
						A_startsound("Gun/Proc",999,0,1);
					}
				  }
			TNT1 A 0 A_ZoomFactor(0.99,ZOOM_INSTANT);
			TNT1 A 0 
			 {
				if(CountInv("Ammotoken") && random(1,5) == 5) 
				{
					A_startsound("ammo/Proc",999,0,0.65);
				}
				else
				{
					A_Takeinventory("GLMag",1,TIF_NOTAKEINFINITE);
				}
			}
			BGLF C 2 bright A_SetPitch(pitch-2, SPF_INTERPOLATE);
			TNT1 A 0 A_FireCustomMissile("GSSpawner",0,0,0,8);
			TNT1 A 0 A_ZoomFactor(1.0);
			BGLF A 4;
			Goto Ready;
		Reload:
			TNT1 A 0 A_JumpIfInventory("GLMode", 1, "ReloadC4");
			TNT1 A 0 A_JumpIf(CountInv("Rockets") == 0,"Ready");
			TNT1 A 0 A_JumpIfInventory("GLMag", 4, 2);
			TNT1 A 0 A_JumpIfInventory("Rockets", 1, "ReloadWork");
			BGLF A 2;
			Goto Ready;
		ReloadWork:
			BGLR ABCD 1;
			TNT1 A 0 A_startsound("Weapons/Grenadeopen",9);
			BGLR EFGH 1;
			BGLR H 4;
		ReloadLoop:
			BGLR IJK 2;
			TNT1 A 0
			{
				A_StartSound("Weapons/Grenadeload",10);
				A_TakeInventory("Rockets",1);
				A_GiveInventory("GLmag",1);
			}
			BGLR LMNO 2;
			BGLR PQR 1;
			BGLR H 4;
			TNT1 A 0 A_Jumpifinventory("GLmag",4,"ReloadEnd");
			TNT1 A 0 A_JumpIf(CountInv("Rockets") == 0,"ReloadEnd");
			Loop;
		ReloadEnd:
			BGLR HGFE 1;
			TNT1 A 0 A_startsound("Weapons/Grenadeclose",9);
			BGLR DCBA 1;
			BGLF A 4;
			Goto Ready;
			
			
		ReloadC4:
			TNT1 A 0 A_JumpIf(CountInv("C4Ammo") == 0,"Ready");
			TNT1 A 0 A_JumpIfInventory("GLMag", 4, 2);
			TNT1 A 0 A_JumpIfInventory("C4Ammo", 1, "ReloadWorkC4");
			BGLF A 2;
			Goto Ready;
		ReloadWorkC4:
			BGLR ABCD 1;
			TNT1 A 0 A_startsound("Weapons/Grenadeopen",9);
			BGLR EFGH 1;
			BGLR H 4;
		ReloadLoopC4:
			BGLR IJK 2;
			TNT1 A 0
			{
				A_StartSound("Weapons/Grenadeload",10);
				A_TakeInventory("C4Ammo",1);
				A_GiveInventory("GLmag",1);
			}
			BGLR LMNO 2;
			BGLR PQR 1;
			BGLR H 4;
			TNT1 A 0 A_Jumpifinventory("GLmag",4,"ReloadEndC4");
			TNT1 A 0 A_JumpIf(CountInv("C4Ammo") == 0,"ReloadEndC4");
			Loop;
		ReloadEndC4:
			BGLR HGFE 1;
			TNT1 A 0 A_startsound("Weapons/Grenadeclose",9);
			BGLR DCBA 1;
			BGLF A 4;
			Goto Ready;
			
		AltFire:
			TNT1 A 0 A_JumpIf(CountInv("GLMode") == 0, "AltFire2");
			BGLR ABCD 1;
			TNT1 A 0 A_Overlay(4, "DetonatePipebombOverlay");
			BGLR EFGH 1;
			BGLR H 18;
			BGLR HGFEDCBA 1;
			Goto Ready;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			GLAN A 1;
			GNAM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			GLAN A 1;
			GNAM AB 1;
			Goto Minethrow;
		Returnstate:
			GNAM BA 1;
			GLAN A 1;
			Goto Ready;
		
		DetonatePipebombOverlay:
			TNT1 A 0
			{
				A_OverlayScale(4, -1, 1, 0);
				A_OverlayOffset(4, 320, 0);
			}
			DETO ABCDE 1;
			DETO E 4;
			DETO EDEFGG 1;
			DETO G 1
			{
				A_GiveInventory("GrenadeDetonator", 1);
				A_startsound("Weapons/pipebutton",10);
			}
			DETO GGFEDCBA 1;
			TNT1 A 0 A_TakeInventory("GrenadeDetonator", 1);
			Stop;

	}
}