class C4LauncherMag : Ammo
{
	Default
	{
	  Inventory.Amount 0;
	  Inventory.MaxAmount 1;
	  Ammo.BackpackAmount 0;
	  Ammo.BackpackMaxAmount 1;
	  Inventory.Icon "AC4BKA0";
	  +INVENTORY.IGNORESKILL;
	}
}

class JustaGL : JustaWeapon
{
	Default
	{
		Weapon.AmmoType1 "C4LauncherMag";
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoType2 "C4Ammo";
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 2;
		Obituary "%k didn't realized non-launched rockets were dangerous.";
		Inventory.PickupSound "weapons/shellslide";
		weapon.slotnumber 6;
		Weapon.SelectionOrder 2300;
		Weapon.SlotPriority 20;
		Inventory.AltHUDIcon "GLAPA0";
		Inventory.pickupmessage "[6] - \c[Rocketcolor]Pipebomb launcher\c- acquired. ";
		Tag "$PC_GRENADELAUNCHERTAG";
		JustaWeapon.BarGraphic "C4Bar";
		JustaWeapon.CaseGraphic "C4";
	}
	
	action void PC_FireGL()
	{
		PC_PlayPowerModSounds();
		
		//A_FireCustomMissile("GSSpawner2",0,0,0,8);
		PC_GunSmoke(0,3,3);
		A_startsound("Weapons/GLfire",10);
		A_AlertMonsters(100);
		
		let plr = PCmarine(self);
		let c4 = A_FireProjectile("ThrownPipebombs");
		plr.ActiveC4.Push(c4);
		c4.vel *= 55;
		
		A_Takeinventory("C4LauncherMag",1,TIF_NOTAKEINFINITE);
	}
	
	action void PC_DetC4() {
		let plr = PCmarine(self);
		for(int i = 0; i < plr.ActiveC4.Size(); i++) {
			let c4 = ThrownPipebombs(plr.ActiveC4[i]);
			if(c4) c4.SetState(c4.FindState("Detonate"));
		}
		plr.ActiveC4.Clear();
	}
	
	States
	{
		Spawn:
			GLAP A -1;
			Stop;
		Select: 
			GNAM BA 1 A_WeaponReady(WRF_NOFIRE);
			Goto ready;
		Deselect: 
			GNAM AB 1;
			TNT1 A 0 A_lower;
			wait;
		Ready:
			GLAN A 1 A_WeaponReady(WRF_ALLOWRELOAD|WRF_ALLOWZOOM|WRF_ALLOWUSER1|WRF_ALLOWUSER2);
			Loop;
		Dryfire:
			GLAN A 16 A_startsound("Weapons/Grenadeempty",11);
			GLAN A 4;
			Goto ready;
		Fire:
			TNT1 A 0 A_jumpifinventory("C4LauncherMag",1,1);
			goto Dryfire;
			GLAF X 1 BRIGHT 
			{
				A_GunFlash();
				PC_FireGL();
			}
			GLAF A 1 bright {
				PC_WeaponRecoil(5, 3);
				A_ZoomFactor(0.99, ZOOM_INSTANT);
			}
			GLAF E 1 A_ZoomFactor(0.999);
			GLAF E 1 A_ZoomFactor(1.0);
			GLAF DCB 1;
			GLAN A 4 A_WeaponReady(WRF_NOPRIMARY);
		Reload:
			TNT1 A 0 A_JumpIf(CountInv("C4Ammo") == 0 || CountInv("C4LauncherMag") > 0,"Ready");
			GLR1 DEF 1;
			GLR1 G 2;
			GLR1 FHIJ 1;
			GLR1 K 2 A_startsound("Weapons/Grenadeopen",9);
			GLR1 LMNO 1;
			GLR1 P 4;
			GLR1 QRSTUV 1;
			GLR1 W 2 {
				A_startsound("Weapons/Grenadeload",10);
				PC_AmmoIntoMag();
			}
			GLR1 XYZ 1;
			GLR2 A 1;
			TNT1 A 2;
			TNT1 A 0 A_startsound("Weapons/Grenadeclose",9);
			GLSA EDCB 1;
			GLAN A 1;
			Goto Ready;
		Altfire:
			GLAN A 1;
			GLR1 CDEF 1;
			TNT1 A 0 A_Overlay(4, "DetonatePipebombOverlay");
		AltLoop:
			GLR1 G 1;
			TNT1 A 0 A_JumpIf(PressingAltfire(), "AltLoop");
			GLR1 G 19;
			GLR1 FEDC 1;
			Goto Ready;
		User1:
			TNT1 A 0 A_JumpIfInventory("HGammo",1,1);
			Goto Ready;
			GLAN A 1;
			GNAM AB 1;
			Goto nadethrow;
		User2:
			TNT1 A 0 A_JumpIfInventory("Mineammo",1,1);
			Goto Ready;
			GLAN A 1;
			GNAM AB 1;
			Goto Minethrow;
		Returnstate:
			GNAM BA 1;
			GLAN A 1;
			Goto Ready;
		
		DetonatePipebombOverlay:
			TNT1 A 0
			{
				A_OverlayScale(4, -1, 1, 0);
				A_OverlayOffset(4, 320, 0);
			}
			DETO ABCDE 1;
			DETO E 2;
		DetLoop:
			DETO E 1;
			TNT1 A 0 A_JumpIf(PressingAltfire(), "DetLoop");
			DETO DEFG 1;
			DETO G 1
			{
				A_startsound("Weapons/pipebutton",10);
				PC_DetC4();
			}
			DETO GFEDCBA 1;
			Stop;
	}
}